<?php
// ============================================================
// DATA PORTOFOLIO — ENGLISH VERSION
// Struktur IDENTIK dengan data_id.php (hanya teks yang diterjemahkan)
// ============================================================

$googleAnalyticsId = 'G-DPC3HR787T';

$profile = [
    'name'          => 'Reynaldi Delphiano',
    'brand'         => 'ReyDel',
    'initial'       => 'RD',
    'eyebrow'       => 'Hello, I\'m',
    'role'          => 'Web & Mobile Developer',
    'role2'         => 'App Developer',
    'location'      => 'Jakarta, Indonesia',
    'languages'     => 'Indonesian (Native), English (Limited Working)',
    'focus'         => 'Web Development, Mobile Apps, UMKM Digital',
    'email'         => 'delphianor@gmail.com',
    'linkedin_url'  => 'https://www.linkedin.com/in/reynaldi-delphiano-2b6b79120',
    'linkedin_name' => 'reynaldi-delphiano',
    'social'        => [
        ['label' => 'Email',       'handle' => 'delphianor@gmail.com',  'url' => 'mailto:delphianor@gmail.com'],
        ['label' => 'WhatsApp',    'handle' => '085155376508',           'url' => 'https://wa.me/6285155376508'],
        ['label' => 'LinkedIn',    'handle' => 'Reynaldi Delphiano',     'url' => 'https://www.linkedin.com/in/reynaldi-delphiano-2b6b79120'],
        ['label' => 'Instagram',   'handle' => '@reynaldi_delphiano_',   'url' => 'https://instagram.com/reynaldi_delphiano'],
        ['label' => 'TikTok',      'handle' => '@rajajasa7',             'url' => 'https://www.tiktok.com/@rajajasa7/'],
        ['label' => 'YouTube',     'handle' => '@reynaldidelphiano5684', 'url' => 'https://www.youtube.com/@reynaldidelphiano5684'],
        ['label' => 'GitHub',      'handle' => 'ReyDel6',                'url' => 'https://github.com/ReyDel6'],
    ],
    'photo'         => 'assets/foto.jpeg',
    'photo_avatar'  => 'assets/foto-pixel.jpg',
    'summary'       => [
        'I am a <strong>Web & Mobile Developer</strong> focused on building web and mobile applications that are functional, responsive, and easy to use. I am experienced in using Laravel/PHP, React, JavaScript, Flutter, MySQL, and REST APIs to turn requirements into digital solutions.',
        'One of the projects I developed is <strong>UMKM Connect</strong>, a digital platform that combines Cashier/POS features, QR Table ordering, and B2B between MSMEs (UMKM). I built this project to help MSME owners manage transactions, receive orders, and connect with business partners more practically.',
        'When developing applications, I am committed to applying clean code, REST API integration, and modern workflows so that every solution stays tidy, efficient, easy to maintain, and aligned with user needs.',
        'Beyond technology, I have cross-field professional experience ranging from sales, operations, banking, technical services, to team leadership. Those experiences shaped my communication, coordination, problem-solving, precision, and adaptability skills, which I apply to every project.',
    ],
];

$projects = [
    [
        'title'    => 'UMKM Connect',
        'tag'      => 'Personal Work • Fullstack',
        'badge'    => 'Registered Copyright',
        'image'    => 'assets/umkm-connect.png',
        'initial'  => 'UMKM Connect',
        'github'   => 'https://github.com/ReyDel6/UMKM_Connect-Web',
        'desc'     => 'A web platform for MSMEs (UMKM) that combines <strong>Cashier/POS</strong>, <strong>QR Table</strong> (order & pay from the customer\'s table), and <strong>B2B between MSMEs</strong> in a single account.',
        'points'   => [
            '<strong>B2B Marketplace</strong> — online store between MSMEs with cart & wholesale checkout.',
            '<strong>QR Table ordering</strong> — customers scan a QR, view the menu, and order & pay online from their smartphone.',
            '<strong>Cashier (POS)</strong> — dashboard, shift management, table orders, & digital cashier ID card.',
            '<strong>Employee Management</strong> — add cashier, cook, waiter, barista, admin (login with 4-digit PIN).',
            '<strong>User-to-user chat</strong> — direct communication between buyers and sellers.',
            '<strong>Products & Stock</strong>, raw materials, incoming orders, & financial reports.',
            '<strong>Multi-role & authentication</strong> — Owner, Admin, Cashier, Supplier, Customer; email login, Google, & password reset.',
            '<strong>Midtrans payments</strong> (Snap) & landing page with a contact-us form.',
        ],
        'meta'     => 'Technology: <strong>Laravel (PHP)</strong>, Blade + Vite, MySQL • Payments <strong>Midtrans</strong> • Registered Copyright <strong>EC002026133137</strong> (2026)',
        'tech'     => [
            'Backend: Laravel (PHP)',
            'Frontend: Blade + Vite, Font Awesome, GSAP',
            'Database: MySQL',
            'Payments: Midtrans Snap API',
        ],
        'roles'    => [
            'Owner/MSME — manages products, stock, employees, and reports.',
            'Admin — assists the owner with store operations.',
            'Cashier — POS cashier, table orders, cashier profile.',
            'Supplier — equivalent to an MSME; their products appear in the marketplace.',
            'Customer — QR table account & online payment with their own dashboard & order history.',
        ],
        'hki'      => 'The <strong>UMKM Connect</strong> project — including source code, interface design, logo, and features — is original work owned by <strong>Reynaldi Delphiano</strong>, protected by copyright and registered with DJKI (HKI <strong>EC002026133137</strong>, 2026). Copying, distributing, or commercializing without the written permission of the rights holder is prohibited.',
        'previews' => [
            ['file' => 'assets/umkm-web-marketplace-preview.png', 'label' => 'UMKM B2B Marketplace'],
            ['file' => 'assets/umkm-web-login-preview.png', 'label' => 'Login Page'],
        ],
    ],
    [
        'title'    => 'Reynaldi Delphiano Portfolio Website',
        'tag'      => 'Personal Work • Reynaldi Delphiano',
        'badge'    => 'Personal Web',
        'image'    => 'assets/portfolio-preview.svg',
        'initial'  => 'RD Portfolio',
        'github'   => 'https://github.com/ReyDel6/ReyPortofolio',
        'live'     => 'http://reydel.page.gd/',
        'desc'     => 'A personal website belonging to <strong>Reynaldi Delphiano</strong> to showcase a professional profile, work experience, education, skills, projects, and certifications in a single responsive page.',
        'points'   => [
            '<strong>Professional profile</strong> — self summary, development focus, and social media contacts.',
            '<strong>Project showcase</strong> — presents UMKM Connect along with its features and documentation.',
            '<strong>Licenses & certifications</strong> — a gallery of certificate images and openable PDF links.',
            '<strong>Responsive design</strong> — adapts to desktop, tablet, and mobile.',
        ],
        'meta'     => 'Technology: <strong>PHP</strong>, HTML, CSS, JavaScript • Data centralized in <strong>data.php</strong>',
        'tech'     => [
            'Backend: PHP',
            'Frontend: HTML, CSS, JavaScript',
            'UI: Responsive design',
            'Deployment: InfinityFree-ready',
        ],
        'preview'       => 'assets/portfolio-home-preview.png',
        'preview_label' => 'Website Preview',
    ],
    [
        'title'    => 'UMKM Connect Mobile',
        'tag'      => 'Personal Work • Mobile Development',
        'badge'    => 'Flutter Mobile App',
        'image'    => 'assets/umkm-connect-mobile.svg',
        'initial'  => 'UMKM Connect Mobile',
        'desc'     => 'A Flutter-based <strong>UMKM Connect</strong> mobile version to help MSMEs manage operations, catalog, stock, transactions, reports, and connections with customers and suppliers from their smartphone.',
        'points'   => [
            '<strong>Cross-platform app</strong> — built with Flutter and Dart for a consistent mobile experience.',
            '<strong>Dashboard & reports</strong> — monitor products, stock, transactions, and sales summaries from a mobile device.',
            '<strong>Multi-role</strong> — supports Owner/MSME, Supplier, and Customer flows with role-based access.',
            '<strong>Customer & Supplier</strong> — customer menu via QR, supplier search, ordering, and user-to-user communication.',
            '<strong>Firebase integration</strong> — authentication, Firestore database, and file storage via Firebase Storage.',
        ],
        'meta'     => 'Technology: <strong>Flutter (Dart)</strong> • Firebase Auth, Firestore, Storage • QR & data reports',
        'tech'     => [
            'Mobile: Flutter + Dart',
            'Backend: Firebase Auth + Firestore',
            'Storage: Firebase Storage',
            'Utilities: QR, Chart, HTTP, Notifications',
        ],
        'hki'      => 'The <strong>UMKM Connect</strong> project, including its source code, interface design, logo, and features, is original work owned by <strong>Reynaldi Delphiano</strong>, protected by copyright and registered with DJKI (HKI <strong>EC002026133137</strong>, 2026).',
        'uiux'     => 'assets/ui-ux-umkm.jpeg',
        'uiux_label'=> 'Mobile UI/UX Design',
        'hki_image'=> 'assets/haki-umkm.jpeg',
        'certificate' => [
            'label'  => 'Champion Certificate',
            'file'   => 'assets/sertifikat-juara.pdf',
        ],
        'download' => [
            'label' => 'Download Android APK',
            'file'  => 'https://github.com/ReyDel6/UMKM_Connect-Web/releases',
        ],
    ],
];

$education = [
    [
        'degree'   => 'Bachelor of Information Systems',
        'school'   => 'Universitas Bina Sarana Informatika (BSI)',
        'date'     => 'Mar 2024 – Mar 2028 (Expected)',
        'icon'     => '🎓',
        'badge'    => 'UBSI',
        'logo'     => 'https://cdn.brandfetch.io/bsi.ac.id/icon',
        'desc'     => 'Studying information systems architecture, software engineering, database management, and enterprise application development.',
    ],
];

$experiences = [
    [
        'title'       => 'PIC (Person In Charge)',
        'track'       => 'Non-IT',
        'org'         => 'PT Hasta Ayu Nusantara',
        'date'        => 'Jan 2026 – Jun 2026',
        'location'    => 'Jakarta, Indonesia',
        'category'    => 'Leadership & Ops',
        'icon'        => '🏢',
        'badge'       => 'HAN',
        'logo'        => 'https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/e3599d10e533038cf5697241dc2851cf.png',
        'items'       => [
            'Fully responsible for managing daily operations, coordinating cross-functional teams, and ensuring project targets are met according to company standards.',
            'Led, directed, and evaluated team member performance to improve productivity and on-site work efficiency.',
            'Served as the main point of contact across divisions and handled operational problem solving tactically.',
            'Managed project administration, periodic reporting, and SOP compliance.',
        ],
    ],
    [
        'title'       => 'Team Leader',
        'track'       => 'Non-IT',
        'org'         => 'Colony Group of Companies (Nescafé)',
        'date'        => 'Jul 2025 – Dec 2025',
        'location'    => 'Pasar Minggu, Jakarta',
        'category'    => 'Leadership & Sales',
        'icon'        => '☕',
        'badge'       => 'Nescafé',
        'logo'        => 'https://cdn.brandfetch.io/nescafe.com/icon',
        'items'       => [
            'Led and supervised field sales / promoter team performance toward Nescafé product sales targets (daily, weekly, monthly).',
            'Coordinated events, exhibitions, and on-field brand activation activities to increase market penetration & brand awareness.',
            'Conducted regular briefings, work performance evaluations, and sales strategy training for the team.',
            'Compiled periodic sales reports, analyzed market trends, and provided tactical recommendations to management.',
        ],
    ],
    [
        'title'       => 'Service Technician (EDC Machines)',
        'track'       => 'IT',
        'org'         => 'PT Bank Central Asia Tbk (BCA)',
        'date'        => 'Sep 2024 – Oct 2024',
        'location'    => 'Kebon Jeruk, Jakarta',
        'category'    => 'Technical & Hardware',
        'icon'        => '🏦',
        'badge'       => 'BCA',
        'logo'        => 'https://cdn.brandfetch.io/bca.co.id/icon',
        'items'       => [
            'Performed periodic maintenance, repairs, new installments (installations), and replacement of EDC machines across BCA merchants.',
            'Ensured network connectivity of EDC terminals and smooth merchant transactions.',
        ],
    ],
    [
        'title'       => 'Service Technician (Smartphone & Gadget)',
        'track'       => 'IT',
        'org'         => 'Laku6.com',
        'date'        => 'Apr 2024 – Sep 2024',
        'location'    => 'Cengkareng, Jakarta',
        'category'    => 'Technical & Hardware',
        'icon'        => '📱',
        'badge'       => 'Laku6',
        'logo'        => 'https://cdn.brandfetch.io/laku6.com/icon',
        'items'       => [
            'Performed in-depth QC & feature testing on smartphones for resale functionality eligibility.',
            'Performed part replacement and hardware repair of mobile phones.',
            'Troubleshooting and resolution of software issues (Android & iOS OS flashing/reset).',
        ],
    ],
    [
        'title'       => 'Marketing Agent Officer',
        'track'       => 'Non-IT',
        'org'         => 'WOM Finance',
        'date'        => 'Jan 2023 – Mar 2023',
        'location'    => 'South Jakarta',
        'category'    => 'Finance & Marketing',
        'icon'        => '💳',
        'badge'       => 'WOM',
        'logo'        => 'https://cdn.brandfetch.io/wom.co.id/icon',
        'items'       => [
            'Managed, developed, and expanded the network of agent partnerships to increase financing application acquisition.',
            'Promoted marketing programs, negotiated partnerships, and performed initial verification of application document eligibility.',
            'Analyzed regional market potential and evaluated partner productivity.',
        ],
    ],
    [
        'title'       => 'Supervisor & Sales Officer',
        'track'       => 'Non-IT',
        'org'         => 'PT Bank Woori Saudara Indonesia 1906, Tbk.',
        'date'        => 'Aug 2022 – Jan 2023',
        'location'    => 'South Jakarta',
        'category'    => 'Finance & Leadership',
        'icon'        => '🏦',
        'badge'       => 'BWS',
        'logo'        => 'https://cdn.brandfetch.io/bankwoorisaudara.com/icon',
        'items'       => [
            'Set marketing strategies for banking products (pension financing) and prepared team activity plans.',
            'Established official cooperation with state institutions for pension financing partnerships.',
            'Implemented an attendance monitoring system and evaluated daily/monthly team target achievement.',
            'Performed customer eligibility surveys, data collection, and telemarketing.',
        ],
    ],
    [
        'title'       => 'Pension Sales Force',
        'track'       => 'Non-IT',
        'org'         => 'PT Bank Syariah Indonesia Tbk (BSI)',
        'date'        => 'May 2022 – Jan 2023',
        'location'    => 'Cipete Selatan, South Jakarta',
        'category'    => 'Finance & Sales',
        'icon'        => '🕌',
        'badge'       => 'BSI',
        'logo'        => 'https://cdn.brandfetch.io/bankbsi.co.id/icon',
        'photos'      => ['assets/experience/bsi.jpeg'],
        'items'       => [
            'Offered and educated customers about sharia financing products specifically for retirees.',
            'Prospected customer data, telemarketing, field surveys, and administrative document collection.',
        ],
    ],
    [
        'title'       => 'Merchant Acquisition Agent',
        'track'       => 'Non-IT',
        'org'         => 'Ralali.com (B2B Marketplace)',
        'date'        => 'May 2022 – Jan 2023',
        'location'    => 'Greater Jakarta',
        'category'    => 'Sales & Business',
        'icon'        => '🛒',
        'badge'       => 'Ralali',
        'logo'        => 'https://cdn.brandfetch.io/ralali.com/icon',
        'items'       => [
            'Conducted field surveys and acquired new merchant/MSME stores to join the Ralali.com B2B ecosystem.',
            'Educated MSME business owners on how the digital B2B wholesale platform works.',
        ],
    ],
    [
        'title'       => 'Sales Consultant',
        'track'       => 'Non-IT',
        'org'         => 'Wuling Motors (Wuling Prima Fatmawati)',
        'date'        => 'Sep 2022 – Dec 2022',
        'location'    => 'South Jakarta',
        'category'    => 'Sales & Business',
        'icon'        => '🚗',
        'badge'       => 'Wuling',
        'logo'        => 'https://cdn.brandfetch.io/wuling.id/icon',
        'photos'      => ['assets/experience/wuling.jpeg'],
        'items'       => [
            'Marketed and sold Wuling car units through online and offline channels.',
            'Represented the dealer at automotive events & exhibitions and accompanied customer test drives.',
        ],
    ],
    [
        'title'       => 'Surveyor - Traffic Counting & Data Collection',
        'track'       => 'Non-IT',
        'org'         => 'Sampingan (Staffinc)',
        'date'        => 'Jan 2022 – Jun 2022',
        'location'    => 'Central & North Jakarta',
        'category'    => 'Research & Data',
        'icon'        => '📈',
        'badge'       => 'Staffinc',
        'logo'        => 'https://cdn.brandfetch.io/staffinc.co/icon',
        'items'       => [
            'Researched and recorded online driver traffic volume at strategic points using a digital counting application.',
            'Compiled daily data verification reports for market research needs.',
        ],
    ],
    [
        'title'       => 'Data Entry',
        'track'       => 'Non-IT',
        'org'         => 'Merdeka Vaccination Program (Polda Metro Jaya)',
        'date'        => 'Aug 2021 & Jan 2022',
        'location'    => 'Cipayung, East Jakarta',
        'category'    => 'Administration & Data',
        'icon'        => '💉',
        'badge'       => 'Polri',
        'logo'        => 'https://upload.wikimedia.org/wikipedia/commons/6/69/Logo_Polri.png',
        'photos'      => ['assets/experience/vaksinasi merdeka.jpeg'],
        'items'       => [
            'Entered vaccination recipient registration data (including the Children\'s Merdeka Vaccination program) into the central system database.',
            'Recapitulated daily digital files with a high level of accuracy.',
        ],
    ],
    [
        'title'       => 'Sorter (Logistics Worker)',
        'track'       => 'Non-IT',
        'org'         => 'Lazada Express',
        'date'        => 'Jan 2019 – Jan 2023',
        'location'    => 'Depok, West Java',
        'category'    => 'Logistics & Operations',
        'icon'        => '📦',
        'badge'       => 'Lazada',
        'logo'        => 'https://cdn.brandfetch.io/lazada.co.id/icon',
        'items'       => [
            'Performed sorting, barcode scanning, and grouping of packages by courier route zones.',
            'Ensured the accuracy of inbound & outbound logistics sorting flow according to SLA targets.',
        ],
    ],
    [
        'title'       => 'Teller (Banking Staff)',
        'track'       => 'Non-IT',
        'org'         => 'PT Bank Central Asia Tbk (BCA)',
        'date'        => 'Sep 2018 – Sep 2019',
        'location'    => 'Sunter, North Jakarta',
        'category'    => 'Banking & Finance',
        'icon'        => '🏦',
        'badge'       => 'BCA',
        'logo'        => 'https://cdn.brandfetch.io/bca.co.id/icon',
        'photos'      => ['assets/experience/bca.jpeg', 'assets/experience/bca2.jpeg'],
        'items'       => [
            'Handled cash and non-cash banking transactions (deposits/withdrawals, clearing, transfers, foreign currency) with 100% accuracy.',
            'Provided Customer Focus oriented Service Excellence and performed cross-selling of banking products.',
            'Ran daily operations in compliance with banking SOPs and prepared end-of-day cash reconciliation.',
        ],
    ],
];

$trainings = [
    [
        'title'       => 'Web Developer',
        'org'         => 'Pusat Pelatihan Kerja Pengembangan Industri (PPKPI)',
        'date'        => 'Jun 2026 – Present',
        'location'    => 'Jakarta, Indonesia',
        'category'    => 'Web Development',
        'icon'        => '💻',
        'badge'       => 'BNSP Certificate',
        'logo'        => 'assets/logo-ppkpi.jpeg',
        'items'       => [
            'Building modern web interfaces using React in a software development training program.',
            'Developing interactive web applications, managing component state, and connecting the frontend with backend/API.',
            'Applying clean code, performance efficiency, and modern development tools.',
        ],
    ],
    [
        'title'       => 'Graphic Designer',
        'org'         => 'Pusat Pelatihan Kerja Pengembangan Industri (PPKPI)',
        'date'        => 'May 2026 – Jun 2026',
        'location'    => 'Jakarta, Indonesia',
        'category'    => 'Graphic Design',
        'icon'        => '🎨',
        'badge'       => 'BNSP Certificate',
        'logo'        => 'assets/logo-ppkpi.jpeg',
        'items'       => [
            'Mastered design principles, typography, and composition to produce aesthetic and communicative visual materials.',
            'Used Adobe Photoshop, Adobe Illustrator, and Adobe InDesign for photos, vectors, logos, illustrations, and multipage documents.',
            'Completed branding projects, flyers, posters, banners, and basic UI for both print and digital media.',
            'Understood the design workflow from concept and execution to pre-press or digital publication.',
        ],
    ],
    [
        'title'       => 'Computer Technician',
        'org'         => 'Pusat Pelatihan Kerja Pengembangan Industri (PPKPI)',
        'date'        => 'Sep 2025 – Sep 2025',
        'location'    => 'East Jakarta',
        'category'    => 'Technical & Hardware',
        'icon'        => '🖥️',
        'badge'       => 'PPKPI',
        'logo'        => 'assets/logo-ppkpi.jpeg',
        'items'       => [
            'Intensive technical training program in the Computer Technician field based on competency.',
            'Mastered assembly, BIOS/UEFI configuration, and computer hardware maintenance.',
            'Operating system installation, driver management, local network configuration, and system performance optimization.',
            'Performed hardware/software failure analysis (troubleshooting) and repairs according to technical standards.',
        ],
    ],
    [
        'title'       => 'Computer Operator',
        'org'         => 'Pusat Pelatihan Kerja Pengembangan Industri (PPKPI)',
        'date'        => 'Oct 2024 – Nov 2024',
        'location'    => 'Cipayung, Jakarta',
        'category'    => 'Technical & Data',
        'icon'        => '📊',
        'badge'       => 'PPKPI',
        'logo'        => 'assets/logo-ppkpi.jpeg',
        'items'       => [
            'Vocational & competency training program in the Computer Operator field.',
            'Advanced Office Suite operation for administrative needs, spreadsheet data analysis, and professional reports.',
            'Computer system management, structured digital file management, and maintenance of productivity support systems.',
        ],
    ],
];

$stats = [

    ['num' => 'HKI', 'label' => 'Registered Copyright', 'sub' => 'Ministry of Law & Human Rights DJKI'],
    ['num' => '13+', 'label' => 'Career History', 'sub' => 'Technical & Managerial'],

];

$skills = [
    ['icon' => '🌐', 'title' => 'Web Front-end', 'desc' => 'React, TypeScript, Next.js, Tailwind, HTML, CSS, JavaScript'],
    ['icon' => '🗄️', 'title' => 'Backend & DB', 'desc' => 'Laravel (PHP), Node.js, MySQL, Firebase'],
    ['icon' => '📱', 'title' => 'Mobile Development', 'desc' => 'Flutter, Dart, Kotlin (Android Studio)'],
    ['icon' => '🧰', 'title' => 'Tools & DevOps', 'desc' => 'Git, GitHub, Docker, Postman, VS Code, Figma'],
    ['icon' => '🎨', 'title' => 'Graphic Design & Office', 'desc' => 'Adobe Photoshop, Illustrator, InDesign, Microsoft Office'],
    ['icon' => '🛠️', 'title' => 'Hardware & Service', 'desc' => 'Computer Troubleshooting, EDC Machine Maintenance, Gadget Repair'],
    ['icon' => '👥', 'title' => 'Leadership & Team', 'desc' => 'Person In Charge (PIC), Team Leader, Team & Field Supervision'],
    ['icon' => '💼', 'title' => 'Business & Banking', 'desc' => 'Banking (BCA Teller), B2B Merchant Acquisition, Field Marketing'],
];

$techSkillPills = [
    ['name' => 'Laravel', 'category' => 'Backend', 'icon' => 'laravel', 'color' => '#f55247'],
    ['name' => 'PHP', 'category' => 'Backend', 'icon' => 'php', 'color' => '#777bb4'],
    ['name' => 'React.js', 'category' => 'Frontend', 'icon' => 'react', 'color' => '#61dafb'],
    ['name' => 'Next.js', 'category' => 'Frontend', 'icon' => 'next', 'color' => '#ffffff'],
    ['name' => 'TypeScript', 'category' => 'Frontend', 'icon' => 'ts', 'color' => '#3178c6'],
    ['name' => 'JavaScript', 'category' => 'Frontend', 'icon' => 'javascript', 'color' => '#f7df1e'],
    ['name' => 'HTML5', 'category' => 'Frontend', 'icon' => 'html', 'color' => '#e34f26'],
    ['name' => 'CSS3', 'category' => 'Frontend', 'icon' => 'css', 'color' => '#1572b6'],
    ['name' => 'TailwindCSS', 'category' => 'Frontend', 'icon' => 'tailwind', 'color' => '#38bdf8'],
    ['name' => 'Bootstrap', 'category' => 'Frontend', 'icon' => 'bootstrap', 'color' => '#7952b3'],
    ['name' => 'Flutter', 'category' => 'Mobile', 'icon' => 'flutter', 'color' => '#02569b'],
    ['name' => 'Kotlin', 'category' => 'Mobile', 'icon' => 'kotlin', 'color' => '#7f52ff'],
    ['name' => 'Android', 'category' => 'Mobile', 'icon' => 'android', 'color' => '#3ddc84'],
    ['name' => 'MySQL', 'category' => 'Backend', 'icon' => 'mysql', 'color' => '#4479a1'],
    ['name' => 'Firebase', 'category' => 'Backend', 'icon' => 'firebase', 'color' => '#ffca28'],
    ['name' => 'Git & GitHub', 'category' => 'Tools', 'icon' => 'git', 'color' => '#f05032'],
    ['name' => 'Docker', 'category' => 'Tools', 'icon' => 'docker', 'color' => '#2496ed'],
    ['name' => 'Postman', 'category' => 'Tools', 'icon' => 'postman', 'color' => '#ff6c37'],
    ['name' => 'Figma', 'category' => 'Tools', 'icon' => 'figma', 'color' => '#f24e1e'],
    ['name' => 'VS Code', 'category' => 'Tools', 'icon' => 'vscode', 'color' => '#007acc'],
    ['name' => 'Microsoft Office', 'category' => 'Tools', 'icon' => 'microsoftoffice', 'local_icon' => 'assets/microsoft-office.svg', 'mark' => 'MS', 'color' => '#f25022'],
    ['name' => 'Adobe Photoshop', 'category' => 'Tools', 'icon' => 'ps', 'color' => '#31a8ff'],
    ['name' => 'Adobe Illustrator', 'category' => 'Tools', 'icon' => 'ai', 'color' => '#ff9a00'],
    ['name' => 'Adobe InDesign', 'category' => 'Tools', 'icon' => 'id', 'local_icon' => 'assets/adobe-indesign.svg', 'mark' => 'Id', 'color' => '#ff3366'],
];

$techIcons = ['laravel','react','php','flutter','firebase','html','css','javascript','mysql','git','docker','ts','next','tailwind','kotlin'];

$certificates = [
    [
        'title' => 'The Role Of CLO as a Strategic Partner',
        'category' => 'Non-IT',
        'issuer' => 'QuBisa',
        'date' => '17 February 2022',
        'credential' => '2U13QBTZ5YOU7H',
        'image' => 'assets/strategic-partner.jpg',
        'file' => 'assets/strategic-partner.jpg',
    ],
    [
        'title' => 'Becoming a Resilient Marketer Aligned with Market Needs',
        'category' => 'Non-IT',
        'issuer' => 'QuBisa',
        'date' => '14 February 2022',
        'credential' => '5NQKDVRENBJBOV',
        'image' => 'assets/marketer-tangguh.jpg',
        'file' => 'assets/marketer-tangguh.jpg',
    ],
    [
        'title' => 'The Importance of Digital Mastery in the Disruption Era',
        'category' => 'IT',
        'issuer' => 'QuBisa',
        'date' => '19 February 2022',
        'credential' => 'G9X4DC0RTJQ9KW',
        'image' => 'assets/penguasaan-digital.jpg',
        'file' => 'assets/penguasaan-digital.jpg',
    ],
    [
        'title' => 'Change or Perish',
        'category' => 'Non-IT',
        'issuer' => 'QuBisa',
        'date' => '16 February 2022',
        'credential' => 'GS2DKUXL5371ML',
        'image' => 'assets/berubah-atau-punah.jpg',
        'file' => 'assets/berubah-atau-punah.jpg',
    ],
    [
        'title' => 'Sensitive-Free Communication',
        'category' => 'Non-IT',
        'issuer' => 'QuBisa',
        'date' => '18 February 2022',
        'credential' => 'QWY91MWP2QIBMW',
        'image' => 'assets/komunikasi-tanpa-sensi.jpg',
        'file' => 'assets/komunikasi-tanpa-sensi.jpg',
    ],
    [
        'title' => 'The Teenagers Character Building Program — Roadmap to Success',
        'category' => 'Non-IT',
        'issuer' => 'Bank Mayora / James Gwee Dream Achievers',
        'date' => '13–14 August 2016',
        'credential' => null,
        'image' => 'assets/roadmap-to-success.jpg',
        'file' => 'assets/roadmap-to-success.jpg',
    ],
    [
        'title' => 'Anti Fraud',
        'category' => 'Non-IT',
        'issuer' => 'Training Certificate',
        'date' => null,
        'credential' => null,
        'image' => 'assets/anti-fraud-preview.png',
        'file' => 'assets/anti-fraud.pdf',
    ],
    [
        'title' => 'API',
        'category' => 'IT',
        'issuer' => 'Training Certificate',
        'date' => null,
        'credential' => null,
        'image' => 'assets/api-preview.png',
        'file' => 'assets/api.pdf',
    ],
    [
        'title' => 'Cyber Security',
        'category' => 'IT',
        'issuer' => 'Training Certificate',
        'date' => null,
        'credential' => null,
        'image' => 'assets/cyber-security-preview.png',
        'file' => 'assets/cyber-security.pdf',
    ],
    [
        'title' => 'Digital Transformation Era',
        'category' => 'IT',
        'issuer' => 'Training Certificate',
        'date' => null,
        'credential' => null,
        'image' => 'assets/digital-transformation-era-preview.png',
        'file' => 'assets/digital-transformation-era.pdf',
    ],
    [
        'title' => 'Behavior at BCA',
        'category' => 'Non-IT',
        'issuer' => 'BCA',
        'date' => null,
        'credential' => null,
        'image' => 'assets/perilaku-di-bca-preview.png',
        'file' => 'assets/perilaku-di-bca.pdf',
    ],
    [
        'title' => 'Award Certificate for Reynaldi Delphiano',
        'category' => 'Non-IT',
        'issuer' => 'Award Certificate',
        'date' => null,
        'credential' => null,
        'image' => 'assets/piagam-penghargaan-reynaldi-delphiano-preview.png',
        'file' => 'assets/piagam-penghargaan-reynaldi-delphiano.pdf',
    ],
    [
        'title' => 'Excel Certificate',
        'category' => 'IT',
        'issuer' => 'Fasz Edu',
        'date' => '8–10 February 2022',
        'credential' => '75/faszedu/OSMM-40/II/2022',
        'image' => 'assets/sertifikat-excel-preview.png',
        'file' => 'assets/sertifikat-excel.pdf',
    ],
    [
        'title' => 'UX Writing',
        'category' => 'IT',
        'issuer' => 'Loker Programmer',
        'date' => '12 February 2022',
        'credential' => '0035/ITUW/PST/LOKPRO/II/2022',
        'image' => 'assets/loker-programmer-ux-writing-preview.png',
        'file' => 'assets/loker-programmer-ux-writing.pdf',
    ],
    [
        'title' => 'Web Developer: The Art of Our Web',
        'category' => 'IT',
        'issuer' => 'Loker Programmer',
        'date' => '5 February 2022',
        'credential' => '0034/WDTAOW/PST/LOKPRO/II/2022',
        'image' => 'assets/loker-programmer-web-developer-preview.png',
        'file' => 'assets/loker-programmer-web-developer.pdf',
    ],
    [
        'title' => 'Children\'s Merdeka Vaccination',
        'category' => 'Non-IT',
        'issuer' => 'Children\'s Merdeka Vaccination Program',
        'date' => null,
        'credential' => null,
        'image' => 'assets/sertifikat-vm-anak-reynaldi-delphiano-preview.png',
        'file' => 'assets/sertifikat-vm-anak-reynaldi-delphiano.pdf',
    ],
];