<?php
// ============================================================
// DATA PORTOFOLIO — edit cukup di file ini, halaman otomatis update
// ============================================================

$googleAnalyticsId = 'G-DPC3HR787T';

$profile = [
    'name'          => 'Reynaldi Delphiano',
    'brand'         => 'ReyDel',
    'initial'       => 'RD',
    'eyebrow'       => 'Halo, saya',
    'role'          => 'Web & Mobile Developer',
    'role2'         => 'Pengembang Aplikasi',
    'location'      => 'Jakarta, Indonesia',
    'languages'     => 'Indonesia (Native), Inggris (Limited Working)',
    'focus'         => 'Web Development, Mobile Apps, UMKM Digital',
    'email'         => 'delphianor@gmail.com',
    'linkedin_url'  => 'https://www.linkedin.com/in/reynaldi-delphiano-2b6b79120',
    'linkedin_name' => 'reynaldi-delphiano',
    'social'        => [
        ['label' => 'Email',       'handle' => 'delphianor@gmail.com',  'url' => 'mailto:delphianor@gmail.com'],
        ['label' => 'WhatsApp',    'handle' => '085155376508',           'url' => 'https://wa.me/6285155376508'],
        ['label' => 'LinkedIn',    'handle' => 'Reynaldi Delphiano',     'url' => 'https://www.linkedin.com/in/reynaldi-delphiano-2b6b79120'],
        ['label' => 'Instagram',   'handle' => '@reynaldi_delphiano_',   'url' => 'https://instagram.com/reynaldi_delphiano'],
        ['label' => 'TikTok',      'handle' => '@rajajasa7',             'url' => 'https://www.tiktok.com/@rajajasa7/'],
        ['label' => 'YouTube',     'handle' => '@reynaldidelphiano5684', 'url' => 'https://www.youtube.com/@reynaldidelphiano5684'],
        ['label' => 'GitHub',      'handle' => 'ReyDel6',                'url' => 'https://github.com/ReyDel6'],
        ['label' => 'Discord',     'handle' => 'delphianor',             'url' => 'https://discord.com/users/delphianor'],
        ['label' => 'Threads',     'handle' => '@reynaldi_delphiano', 'url' => 'https://www.threads.com/@reynaldi_delphiano'],
    ],
    'photo'         => 'assets/foto.jpeg',
    'photo_avatar'  => 'assets/foto-pixel.jpg',
    'summary'       => [
        'Saya seorang <strong>Web & Mobile Developer</strong> yang berfokus membangun aplikasi web dan mobile yang fungsional, responsif, serta mudah digunakan. Saya terbiasa menggunakan Laravel/PHP, React, JavaScript, Flutter, MySQL, dan REST API untuk mengubah kebutuhan menjadi solusi digital.',
        'Salah satu proyek yang saya kembangkan adalah <strong>UMKM Connect</strong>, platform digital yang menggabungkan fitur Kasir/POS, QR Meja, dan B2B antar-UMKM. Proyek ini saya bangun untuk membantu pelaku UMKM mengelola transaksi, menerima pesanan, dan terhubung dengan mitra usaha secara lebih praktis.',
        'Dalam mengembangkan aplikasi, saya berkomitmen menerapkan clean code, integrasi REST API, dan workflow modern agar setiap solusi yang dibangun tetap rapi, efisien, mudah dikembangkan, dan sesuai dengan kebutuhan pengguna.',
        'Di luar bidang teknologi, saya memiliki pengalaman profesional lintas bidang, mulai dari penjualan, operasional, perbankan, layanan teknis, hingga kepemimpinan tim. Pengalaman tersebut membentuk kemampuan komunikasi, koordinasi, problem solving, ketelitian, dan adaptasi yang saya terapkan dalam setiap proyek.',
    ],
];

$services = [
    [
        'icon'  => '🛒',
        'title' => 'Aplikasi Kasir (POS) & Toko Online',
        'desc'  => 'Point of sale, katalog produk, promo & paket, poin member, dan pembayaran QRIS — fullstack (React + Laravel).',
        'href'  => 'project-detail.php?p=2',
        'cta'   => 'Lihat contoh (POSMart) →',
    ],
    [
        'icon'  => '📱',
        'title' => 'Aplikasi Mobile UMKM',
        'desc'  => 'Flutter cross-platform untuk mengelola katalog, stok, transaksi, dan laporan langsung dari genggaman.',
        'href'  => 'project-detail.php?p=4',
        'cta'   => 'Lihat contoh (Mobile) →',
    ],
    [
        'icon'  => '🌐',
        'title' => 'Website Bisnis & Portofolio',
        'desc'  => 'Company profile, landing page, dan website portofolio yang responsif, cepat, dan bilingual (ID/EN).',
        'href'  => 'project-detail.php?p=3',
        'cta'   => 'Lihat contoh (Web Ini) →',
    ],
    [
        'icon'  => '🔌',
        'title' => 'REST API & Integrasi',
        'desc'  => 'Backend Laravel, REST API yang rapi, autentikasi (Google OAuth), dan integrasi pembayaran Midtrans.',
        'href'  => 'project-detail.php?p=1',
        'cta'   => 'Lihat contoh (UMKM Connect) →',
    ],
    [
        'icon'  => '🛠️',
        'title' => 'Maintenance & Pengembangan Lanjutan',
        'desc'  => 'Perawatan berkala, update fitur, perbaikan bug, keamanan, dan pengembangan fitur tambahan.',
        'href'  => 'contact.php',
        'cta'   => 'Diskusikan kebutuhan →',
    ],
];

$projects = [
    [
        'title'    => 'PPDB SMK Nusantara Bangsa',
        'tag'      => 'Karya Pribadi • Web Development',
        'badge'    => 'Web PPDB Online',
        'image'    => 'assets/smk-nusantara-logo.svg',
        'initial'  => 'PPDB SMK',
        'github'   => 'https://github.com/ReyDel6/ppdb-sekolah-web',
        'desc'     => 'Sistem <strong>PPDB Online</strong> dan <strong>manajemen akademik sekolah</strong> SMK Nusantara Bangsa — proyek <strong>Uji Kompetensi Keahlian (UJK/UKK RPL)</strong>. Mengelola pendaftaran calon siswa lewat form bertahap dengan unggah berkas, gelombang & kuota jurusan, verifikasi hingga daftar ulang, portal cek status & cetak kartu peserta ber-QR, dashboard multi-role, plus modul akademik (absensi, nilai, jadwal), keuangan SPP, e-learning & e-library dengan ekspor rekap/rapor Excel dan PDF.',
        'points'   => [
            '<strong>Multi-role & autentikasi</strong> — 6 peran: Admin, Panitia, Guru, Siswa, Orang Tua, dan Kepala Sekolah (Laravel Breeze + middleware role).',
            '<strong>Pendaftaran bertahap</strong> — data diri, pilihan jurusan, data orang tua, unggah berkas (pas foto, KK, ijazah) & pratinjau; dukungan gelombang & kuota per jurusan.',
            '<strong>Portal cek status publik</strong> — pantau status pendaftaran real-time & cetak kartu peserta dengan QR Code.',
            '<strong>Dashboard analitik & kepala sekolah</strong> — kuota per jurusan, persentase diterima/cadangan/tolak, grafik (Chart.js), statistik PPDB, kurikulum & kepegawaian.',
            '<strong>Manajemen akademik</strong> — kelas, mata pelajaran, guru, siswa & jadwal; absensi (Hadir/Izin/Sakit/Alpha/Terlambat); penilaian & rapor.',
            '<strong>Ekspor rekap & rapor</strong> — rekap pendaftar, nilai & absensi dalam Excel dan PDF (Dompdf).',
            '<strong>Keuangan SPP</strong> — tarif per kelas, generate tagihan bulanan & pembayaran (Tunai/Transfer/Online) lewat admin dan portal siswa/orang tua.',
            '<strong>E-learning & e-library</strong> — materi, tugas, forum kelas; katalog buku & peminjaman.',
        ],
        'tech'     => [
            'Backend: Laravel (PHP) + MySQL',
            'Frontend: Blade + Vite, Tailwind CSS, Alpine.js',
            'Laporan: Laravel Excel + Dompdf (PDF)',
            'QR Code: qrcodejs',
            'Grafik: Chart.js',
        ],
        'previews' => [
            ['file' => 'assets/ppdb-home-preview.png', 'label' => 'Landing Page'],
            ['file' => 'assets/ppdb-login-preview.png', 'label' => 'Halaman Login'],
        ],
    ],
    [
        'title'    => 'UMKM Connect',
        'tag'      => 'Karya Pribadi • Fullstack',
        'badge'    => 'Hak Cipta Terdaftar',
        'image'    => 'assets/umkm-connect.png',
        'initial'  => 'UMKM Connect',
        'github'   => 'https://github.com/ReyDel6/UMKM_Connect-Web',
        'desc'     => 'Platform web untuk UMKM yang memadukan <strong>Kasir/POS</strong>, <strong>QR Meja</strong> (pesan & bayar dari meja pelanggan), dan <strong>B2B antar-UMKM</strong> dalam satu akun.',
        'points'   => [
            '<strong>Marketplace B2B</strong> — toko online antar-UMKM dengan keranjang & checkout grosir.',
            '<strong>Pesan via QR Meja</strong> — pelanggan scan QR, lihat menu, pesan & bayar online dari smartphone.',
            '<strong>Kasir (POS)</strong> — dashboard, manajemen shift, pesanan meja, & ID card digital kasir.',
            '<strong>Manajemen Karyawan</strong> — tambah kasir, koki, pelayan, barista, admin (login via PIN 4 digit).',
            '<strong>Chat antar-pengguna</strong> — komunikasi langsung pembeli & penjual.',
            '<strong>Produk & Stok</strong>, bahan baku, pesanan masuk, & laporan keuangan.',
            '<strong>Multi-role & autentikasi</strong> — Owner, Admin, Cashier, Supplier, Customer; login email, Google, & reset password.',
            '<strong>Pembayaran Midtrans</strong> (Snap) & landing page dengan form hubungi kami.',
        ],
        'meta'     => 'Teknologi: <strong>Laravel (PHP)</strong>, Blade + Vite, MySQL • Pembayaran <strong>Midtrans</strong> • Terdaftar Hak Cipta <strong>EC002026133137</strong> (2026)',
        'tech'     => [
            'Backend: Laravel (PHP)',
            'Frontend: Blade + Vite, Font Awesome, GSAP',
            'Database: MySQL',
            'Pembayaran: Midtrans Snap API',
        ],
        'roles'    => [
            'Owner/UMKM — kelola penuh produk, stok, karyawan, laporan.',
            'Admin — membantu owner dalam operasional toko.',
            'Cashier — kasir (POS), pesanan meja, profil kasir.',
            'Supplier — setara UMKM; produknya tampil di marketplace.',
            'Customer — akun scan QR meja & pembayaran online dengan dashboard & riwayat order sendiri.',
        ],
        'hki'      => 'Proyek <strong>UMKM Connect</strong> — termasuk source code, desain antarmuka, logo, dan fitur — adalah karya orisinal milik <strong>Reynaldi Delphiano</strong>, dilindungi Hak Cipta dan dicatatkan di DJKI (HKI <strong>EC002026133137</strong>, 2026). Dilarang menggandakan, mendistribusikan, atau mengomersialkan tanpa izin tertulis pemegang hak.',
'previews' => [
            ['file' => 'assets/umkm-web-login-preview.webp', 'label' => 'Halaman Login'],
        ],
    ],
    [
        'title'    => 'POSMart',
        'tag'      => 'Karya Pribadi • Fullstack',
        'badge'    => 'Point of Sale',
        'image'    => 'assets/posmart-preview.svg',
        'logo'     => 'assets/posmart-logo.svg',
        'initial'  => 'POSMart',
        'github'   => 'https://github.com/ReyDel6/POSMART',
        'desc'     => 'Aplikasi <strong>Point of Sale (POS) + Minimarket Digital</strong> berbasis web: manajemen penjualan, produk, stok, zona pengiriman, dan laporan — lengkap dengan storefront publik, promo & paket, poin member, hingga pembayaran QRIS (Midtrans).',
        'points'   => [
            '<strong>Storefront minimarket</strong> — katalog produk, pencarian & filter kategori, halaman detail produk, hero promo & marquee, paket bundling, dan ulasan produk dari pembeli.',
            '<strong>Multi-role lengkap</strong> — Admin (produk, promo, zona ongkir, staf), Kasir (POS cepat), Owner (laporan & analitik restock), Supplier (produk tampil di marketplace), Customer (dashboard pesanan sendiri).',
            '<strong>Kasir modern</strong> — keranjang belanja, diskon, invoice QRIS/Midtrans, dan manajemen pesanan real-time.',
            '<strong>Poin &amp; loyalitas</strong> — koin member terkumpul di tiap transaksi dan bisa dipakai sebagai diskon.',
            '<strong>Desain Modern Neo-Bold</strong> — frontend dirombak total: palet krem, aksen neon, hard shadow, tipografi tegas, dan responsif penuh.',
        ],
        'meta'     => 'Teknologi: <strong>React + Vite + Tailwind CSS 4 (Frontend)</strong> • <strong>Laravel (PHP API Backend)</strong> • MySQL • Google OAuth • Midtrans QRIS • Multi-role',
        'tech'     => [
            'Frontend: React.js + Vite, Tailwind CSS 4, Material Tailwind',
            'Backend: Laravel (PHP) — REST API',
            'Database: MySQL',
            'Pembayaran: QRIS Midtrans · Auth: Google OAuth + Email/Password',
        ],
        'roles'    => [
            'Admin — kelola pengguna, produk, promo, kategori, dan zona pengiriman.',
            'Kasir — transaksi penjualan cepat melalui antarmuka POS.',
            'Owner — laporan penjualan, analitik stok, dan rekap usaha.',
            'Supplier — produk dapat ditampilkan sebagai marketplace.',
            'Customer — akun scan QR meja, pembayaran online, dan dashboard riwayat pesanan.',
        ],
'previews' => [
            ['file' => 'assets/posmart-catalog-preview.png', 'label' => 'Storefront & Kasir (desain Neo-Bold)'],
            ['file' => 'assets/posmart-products-preview.png', 'label' => 'Manajemen Produk (Panel Admin)'],
            ['file' => 'assets/posmart-login-preview.png', 'label' => 'Halaman Login'],
        ],
    ],
[
        'title'    => 'Website Portfolio Reynaldi Delphiano',
        'tag'      => 'Karya Pribadi • Reynaldi Delphiano',
        'badge'    => 'Personal Web',
        'image'    => 'assets/portfolio-preview.svg',
        'logo'     => 'assets/reydel-logo.svg',
        'initial'  => 'RD Portfolio',
        'github'   => 'https://github.com/ReyDel6/ReyPortofolio',
        'live'     => 'http://reydel.page.gd/',
        'desc'     => 'Website personal milik <strong>Reynaldi Delphiano</strong> untuk menampilkan profil profesional, pengalaman kerja, pendidikan, skill, proyek, dan sertifikasi dalam satu halaman yang responsif.',
        'points'   => [
            '<strong>Profil profesional</strong> — ringkasan diri, fokus pengembangan, dan kontak sosial media.',
            '<strong>Showcase proyek</strong> — menampilkan UMKM Connect beserta fitur dan dokumentasinya.',
            '<strong>Lisensi & sertifikasi</strong> — galeri gambar sertifikat dan link PDF yang dapat dibuka.',
            '<strong>Responsive design</strong> — tampilan menyesuaikan desktop, tablet, dan mobile.',
        ],
        'meta'     => 'Teknologi: <strong>PHP</strong>, HTML, CSS, JavaScript • Data terpusat di <strong>data.php</strong>',
        'tech'     => [
            'Backend: PHP',
            'Frontend: HTML, CSS, JavaScript',
            'UI: Responsive design',
            'Deployment: InfinityFree-ready',
        ],
        'preview'       => 'assets/portfolio-home-preview.png',
        'preview_label' => 'Preview Website',
    ],
    [
        'title'    => 'UMKM Connect Mobile',
        'tag'      => 'Karya Pribadi • Mobile Development',
        'badge'    => 'Flutter Mobile App',
        'image'    => 'assets/umkm-connect-mobile.svg',
        'logo'     => 'assets/umkm-connect-logo.png',
        'initial'  => 'UMKM Connect Mobile',
        'desc'     => 'Versi mobile <strong>UMKM Connect</strong> berbasis Flutter untuk membantu UMKM mengelola operasional, katalog, stok, transaksi, laporan, serta koneksi dengan customer dan supplier melalui smartphone.',
        'points'   => [
            '<strong>Aplikasi cross-platform</strong> — dikembangkan dengan Flutter dan Dart untuk pengalaman mobile yang konsisten.',
            '<strong>Dashboard & laporan</strong> — memantau produk, stok, transaksi, dan ringkasan penjualan dari perangkat mobile.',
            '<strong>Multi-role</strong> — mendukung alur Owner/UMKM, Supplier, dan Customer dengan akses sesuai kebutuhan.',
            '<strong>Customer & Supplier</strong> — menu pelanggan via QR, pencarian supplier, pemesanan, dan komunikasi antar-pengguna.',
            '<strong>Firebase terintegrasi</strong> — autentikasi, database Firestore, dan penyimpanan file melalui Firebase Storage.',
        ],
        'meta'     => 'Teknologi: <strong>Flutter (Dart)</strong> • Firebase Auth, Firestore, Storage • QR & laporan data',
        'tech'     => [
            'Mobile: Flutter + Dart',
            'Backend: Firebase Auth + Firestore',
            'Storage: Firebase Storage',
            'Utilities: QR, Chart, HTTP, Notifications',
        ],
        'hki'      => 'Proyek <strong>UMKM Connect</strong> beserta source code, desain antarmuka, logo, dan fiturnya adalah karya orisinal milik <strong>Reynaldi Delphiano</strong>, dilindungi Hak Cipta dan dicatatkan di DJKI (HKI <strong>EC002026133137</strong>, 2026).',
        'uiux'     => 'assets/ui-ux-umkm.jpeg',
        'uiux_label'=> 'Desain UI/UX Mobile',
        'hki_image'=> 'assets/haki-umkm.jpeg',
        'certificate' => [
            'label'  => 'Sertifikat Juara',
            'file'   => 'assets/sertifikat-juara.pdf',
        ],
'download' => [
            'label' => 'Unduh APK Android',
            'file'  => 'https://github.com/ReyDel6/UMKM_Connect-Web/releases',
        ],
    ],
    [
        'title'    => 'Garuda Riders Motorcycle Club',
        'tag'      => 'Karya Pribadi • Website Komunitas',
        'badge'    => 'Web Komunitas',
        'image'    => 'assets/garuda-riders-logo.png',
        'initial'  => 'Garuda Riders',
        'github'   => 'https://github.com/ReyDel6/garuda-riders',
        'desc'     => 'Website resmi <strong>Garuda Riders Motorcycle Club</strong> — komunitas motor aktif sejak 2015. Menampilkan profil komunitas, visi, galeri foto & video, agenda event, artikel, klien/mitra, dan form kontak, dengan <strong>admin CMS</strong> untuk mengelola seluruh konten.',
        'points'   => [
            '<strong>Profil & visi komunitas</strong> — kisah, sejarah, dan visi komunitas motor aktif sejak 2015.',
            '<strong>Galeri foto & video</strong> — mendukung upload gambar dan video MP4 dengan keterangan.',
            '<strong>Agenda event</strong> — daftar event mendatang & lampau lengkap dengan halaman detail.',
            '<strong>Artikel/blog</strong> — sistem berita dengan halaman detail berbasis slug.',
            '<strong>Klien & mitra</strong> — showcase logo partner dan produk/jasa komunitas.',
            '<strong>Form kontak</strong> — tersimpan ke database dengan notifikasi email admin.',
            '<strong>Admin CMS</strong> — CRUD artikel, event, galeri, klien, dan kotak masuk pesan.',
        ],
        'tech'     => [
            'Backend: Laravel 13 (PHP 8.3), Eloquent ORM',
            'Frontend: Blade + Tailwind CSS (tema navy & gold), Alpine.js, Vite',
            'Database: MySQL',
            'Auth: Laravel Breeze (login, register, profil)',
        ],
        'previews' => [
            ['file' => 'assets/garudariders-home.webp', 'label' => 'Halaman Depan'],
        ],
    ],
    [
        'title'    => 'Plantify',
        'tag'      => 'Karya Pribadi • Web & Mobile',
        'badge'    => 'Hybrid Mobile App',
        'image'    => 'assets/plantify-icon.svg',
        'initial'  => 'Plantify',
        'github'   => 'https://github.com/ReyDel6/Plantify',
        'desc'     => 'Aplikasi <strong>identifikasi & perawatan tanaman</strong> dengan tampilan mobile-first, dikembangkan menggunakan Laravel + React, dan dikemas sebagai <strong>hybrid Android via Capacitor</strong> serta PWA.',
        'points'   => [
            '<strong>Onboarding</strong> — intro 3 slide bertema botani "Enjoy your Life with Plants".',
            '<strong>Identifikasi tanaman</strong> — kuesioner ciri daun, cahaya, dan kebutuhan air untuk mencocokkan spesies.',
            '<strong>Koleksi tanaman</strong> — kartu koleksi dengan status penyiraman & kesehatan.',
            '<strong>Pengingat perawatan</strong> — jadwal siram, pupuk, dan repot dengan notifikasi web push (VAPID).',
            '<strong>Autentikasi lengkap</strong> — login/signup, Facebook OAuth, passkey (WebAuthn), verifikasi email, 2FA.',
            '<strong>Offline-first & PWA</strong> — sinkronisasi state tersimpan lokal + service worker.',
            '<strong>Dua bahasa & tema</strong> — Indonesia/English serta mode terang/gelap.',
        ],
        'tech'     => [
            'Backend: Laravel 13 + Laravel Fortify, Inertia',
            'Frontend: React 19 + TypeScript, Tailwind CSS 4, shadcn/Radix UI',
            'Mobile: Capacitor 8 (Android) + PWA',
            'Database: MySQL; Push: Web Push (VAPID)',
        ],
        'previews' => [
            ['file' => 'assets/plantify-login.webp', 'label' => 'Halaman Login'],
            ['file' => 'assets/plantify-onboarding.webp', 'label' => 'Onboarding'],
        ],
    ],
    [
        'title'    => 'Smart Warung Madura',
        'tag'      => 'Karya Pribadi • Web App',
        'badge'    => 'Kiosk Self-Checkout',
        'image'    => 'assets/smartwarung-icon.svg',
        'initial'  => 'Smart Warung',
        'desc'     => 'Kiosk <strong>self-checkout untuk warung 24 jam</strong> — pelanggan memilih produk di katalog layar sentuh, checkout via <strong>QRIS</strong> atau tunai, lalu menerima <strong>struk digital</strong>; admin mengelola produk dan kode QR merchant.',
        'points'   => [
            '<strong>Katalog dinamis</strong> — nama produk, harga, stok, dan gambar dari database.',
            '<strong>Keranjang belanja</strong> — tambah/hapus item dengan total otomatis.',
            '<strong>Pembayaran QRIS & tunai</strong> — QR merchant + timer hitung mundur 2 menit.',
            '<strong>Struk digital</strong> — struk bergaya mesin cetak setelah checkout berhasil.',
            '<strong>Stok transaksional</strong> — pengurangan stok dalam database transaction (rollback saat gagal).',
            '<strong>Admin panel</strong> — CRUD produk dengan upload gambar & kelola QRIS merchant.',
        ],
        'tech'     => [
            'Backend: Laravel 12 (PHP 8.2)',
            'Frontend: Blade + custom CSS (Poppins, glassmorphism), Vanilla JS',
            'Database: MySQL',
            'Fitur: Pembayaran QRIS, struk digital, transaksi stok',
        ],
        'previews' => [
            ['file' => 'assets/smartwarung-home.webp', 'label' => 'Kiosk Self-Checkout'],
        ],
    ],
    [
        'title'    => 'Toko Online',
        'tag'      => 'Studi Kasus • E-Commerce',
        'badge'    => 'E-Commerce',
        'image'    => 'assets/tokoonline-logo.png',
        'initial'  => 'Toko Online',
        'desc'     => 'Aplikasi <strong>toko online (e-commerce)</strong> dengan katalog produk, keranjang berbasis sesi, checkout tanpa login, perhitungan ongkir real-time via <strong>RajaOngkir</strong>, dan <strong>admin panel</strong> lengkap dengan laporan & grafik.',
        'points'   => [
            '<strong>Katalog & produk</strong> — daftar, detail, dan filter kategori.',
            '<strong>Keranjang sesi</strong> — tambah, ubah jumlah (validasi stok), dan hapus item.',
            '<strong>Checkout tamu</strong> — form tervalidasi (nama, telepon, alamat, kota/kodepos).',
            '<strong>Ongkir RajaOngkir API</strong> — pilih provinsi/kota dan hitung biaya kirim.',
            '<strong>Login Google</strong> (Socialite) & area akun customer.',
            '<strong>Admin panel</strong> — CRUD produk (multi foto), kategori, customer, kelola order + resi, laporan cetak, dan grafik penjualan bulanan.',
        ],
        'tech'     => [
            'Backend: Laravel 10 (PHP 8.1+), Eloquent ORM',
            'Frontend: Blade + template storefront eShop & admin matrix-admin',
            'Integrasi: RajaOngkir API, Google OAuth (Laravel Socialite)',
            'Database: MySQL',
        ],
        'previews' => [
            ['file' => 'assets/tokoonline-home.webp', 'label' => 'Halaman Depan Toko'],
        ],
    ],
    [
        'title'    => 'Gudang Gadget',
        'tag'      => 'Karya Pribadi • Web App',
        'badge'    => 'Manajemen Gudang',
        'image'    => 'assets/webgudang-icon.svg',
        'initial'  => 'Gudang Gadget',
        'github'   => 'https://github.com/ReyDel6/gudang-gadget',
        'desc'     => 'Aplikasi <strong>manajemen gudang & inventori gadget</strong> — kelola produk, stok, kategori, riwayat aktivitas stok, dan pengguna, lengkap dengan dashboard statistik dan grafik.',
        'points'   => [
            '<strong>Dashboard</strong> — kartu statistik (total produk, stok, kategori, alert stok habis) + grafik Chart.js.',
            '<strong>CRUD inventori</strong> — produk dengan foto, kategori auto-suggestion, dan status (Tersedia/Habis/Tidak Dijual).',
            '<strong>Kontrol & log stok</strong> — tombol +/− dengan riwayat perubahan (before/after, delta, user).',
            '<strong>Manajemen pengguna</strong> — CRUD admin dengan guard (tidak bisa hapus diri sendiri / user terakhir).',
            '<strong>Autentikasi</strong> — login/logout, lupa & reset password.',
            '<strong>Ekspor & cetak</strong> — pencarian live, filter kategori, ekspor CSV, laporan cetak landscape.',
        ],
        'tech'     => [
            'Backend: Laravel 13 (PHP 8.3)',
            'Frontend: Blade + Tailwind CSS 4, Chart.js, Vite',
            'Database: MySQL',
            'Fitur: Export CSV, laporan cetak, log aktivitas',
        ],
        'previews' => [
            ['file' => 'assets/gudang-login.webp', 'label' => 'Halaman Login'],
        ],
    ],
    [
        'title'    => 'Undangan Pernikahan Digital',
        'tag'      => 'Karya Pribadi • Web Development',
        'badge'    => 'Undangan Digital',
        'image'    => 'assets/undangan-preview.svg',
        'logo'     => 'assets/undangan-logo.svg',
        'initial'  => 'Undangan',
        'github'   => 'https://github.com/ReyDel6/wedding-invitation',
        'live'     => 'https://undangan-nikah-ruby.vercel.app',
        'desc'     => 'Aplikasi <strong>undangan pernikahan digital</strong> interaktif satu halaman berbasis <strong>React + Vite + Tailwind CSS 4</strong> — layar pembuka dengan foto pasangan, musik latar, countdown, rangkaian acara, galeri, RSVP WhatsApp, amplop digital, dan ucapan & doa tamu, dengan seluruh data dikelola lewat satu file config.',
        'points'   => [
            '<strong>Layar pembuka</strong> — foto pasangan berbingkai emas, tombol "Buka Undangan", dan sapaan tamu personal via <code>?to=Nama</code>.',
            '<strong>Musik latar</strong> — auto-play dengan tombol mute melayang di pojok layar.',
            '<strong>Countdown real-time</strong> — hitung mundur menuju hari pernikahan.',
            '<strong>Rangkaian acara</strong> — jadwal Akad & Resepsi lengkap dengan venue dan tautan Google Maps.',
            '<strong>RSVP ke WhatsApp</strong> — konfirmasi kehadiran otomatis tanpa backend.',
            '<strong>Amplop digital</strong> — nomor rekening, tombol salin, dan gambar QRIS.',
            '<strong>Ucapan & doa</strong> — tamu menulis doa yang tersimpan di localStorage per perangkat.',
            '<strong>Desain elegan</strong> — palet cream & emas, tipografi Playfair Display, dan animasi kelopak bunga.',
        ],
        'meta'     => 'Teknologi: <strong>React 19 + Vite + Tailwind CSS 4</strong> • lucide-react • Google Fonts • Deploy statis',
        'tech'     => [
            'Frontend: React 19 + Vite',
            'Styling: Tailwind CSS 4 (@theme custom palette)',
            'Icons: lucide-react',
            'Fonts: Playfair Display & Inter (Google Fonts)',
            'Deploy: static build (dist/) — Vercel/Netlify/GitHub Pages ready',
        ],
        'previews' => [
            ['file' => 'assets/undangan-cover-preview.png', 'label' => 'Layar Pembuka (Cover)'],
            ['file' => 'assets/undangan-invitation-preview.png', 'label' => 'Halaman Undangan (Mobile)'],
        ],
    ],
];

$education = [
    [
        'degree'   => 'S1 Sistem Informasi',
        'school'   => 'Universitas Bina Sarana Informatika (BSI)',
        'date'     => 'Mar 2024 – Mar 2028 (Diharapkan)',
        'icon'     => '🎓',
        'badge'    => 'UBSI',
        'logo'     => 'https://cdn.brandfetch.io/bsi.ac.id/icon',
        'desc'     => 'Mempelajari arsitektur sistem informasi, rekayasa perangkat lunak, manajemen basis data, dan pengembangan aplikasi enterprise.',
    ],
];

$experiences = [
    [
        'title'       => 'PIC (Person In Charge)',
        'track'       => 'Non-IT',
        'org'         => 'PT Hasta Ayu Nusantara',
        'date'        => 'Jan 2026 – Jun 2026',
        'location'    => 'Jakarta, Indonesia',
        'category'    => 'Leadership & Ops',
        'icon'        => '🏢',
        'badge'       => 'HAN',
        'logo'        => 'https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/e3599d10e533038cf5697241dc2851cf.png',
        'items'       => [
            'Bertanggung jawab penuh mengelola operasional harian, koordinasi tim lintas fungsi, dan memastikan pencapaian target proyek sesuai standar perusahaan.',
            'Memimpin, mengarahkan, dan mengevaluasi kinerja anggota tim guna meningkatkan produktivitas serta efisiensi kerja di lapangan.',
            'Menjadi point of contact utama lintas divisi serta menangani problem solving operasional secara taktis.',
            'Mengelola administrasi proyek, penyusunan laporan berkala, dan kepatuhan SOP operasional.',
        ],
    ],
    [
        'title'       => 'Team Leader',
        'track'       => 'Non-IT',
        'org'         => 'Colony Group of Companies (Nescafé)',
        'date'        => 'Jul 2025 – Des 2025',
        'location'    => 'Pasar Minggu, Jakarta',
        'category'    => 'Leadership & Sales',
        'icon'        => '☕',
        'badge'       => 'Nescafé',
        'logo'        => 'https://cdn.brandfetch.io/nescafe.com/icon',
        'items'       => [
            'Memimpin dan mengawasi kinerja tim field sales / promoter untuk target penjualan produk Nescafé (harian, mingguan, bulanan).',
            'Mengkoordinasikan event, pameran, dan kegiatan brand activation di lapangan guna meningkatkan penetrasi pasar & brand awareness.',
            'Melakukan briefing rutin, evaluasi performa kerja, dan pelatihan strategi penjualan tim.',
            'Menyusun sales report berkala, menganalisis tren pasar, dan memberikan rekomendasi taktis ke manajemen.',
        ],
    ],
    [
        'title'       => 'Service Technician (Mesin EDC)',
        'track'       => 'IT',
        'org'         => 'PT Bank Central Asia Tbk (BCA)',
        'date'        => 'Sep 2024 – Okt 2024',
        'location'    => 'Kebon Jeruk, Jakarta',
        'category'    => 'Teknis & Hardware',
        'icon'        => '🏦',
        'badge'       => 'BCA',
        'logo'        => 'https://cdn.brandfetch.io/bca.co.id/icon',
        'items'       => [
            'Melakukan maintenance berkala, perbaikan, installment (pemasangan baru), dan replace mesin EDC di berbagai merchant BCA.',
            'Memastikan konektivitas jaringan terminal EDC dan kelancaran transaksi merchant.',
        ],
    ],
    [
        'title'       => 'Service Technician (Smartphone & Gadget)',
        'track'       => 'IT',
        'org'         => 'Laku6.com',
        'date'        => 'Apr 2024 – Sep 2024',
        'location'    => 'Cengkareng, Jakarta',
        'category'    => 'Teknis & Hardware',
        'icon'        => '📱',
        'badge'       => 'Laku6',
        'logo'        => 'https://cdn.brandfetch.io/laku6.com/icon',
        'items'       => [
            'Melakukan QC & feature testing mendalam pada smartphone untuk kelayakan fungsi jual-beli kembali.',
            'Melakukan pergantian dan repair sparepart hardware handphone.',
            'Troubleshooting dan penyelesaian masalah software (OS Android & iOS flashing/reset).',
        ],
    ],
    [
        'title'       => 'Marketing Agent Officer',
        'track'       => 'Non-IT',
        'org'         => 'WOM Finance',
        'date'        => 'Jan 2023 – Mar 2023',
        'location'    => 'Jakarta Selatan',
        'category'    => 'Finance & Marketing',
        'icon'        => '💳',
        'badge'       => 'WOM',
        'logo'        => 'https://cdn.brandfetch.io/wom.co.id/icon',
        'items'       => [
            'Mengelola, mengembangkan, dan memperluas jaringan kemitraan agen untuk meningkatkan perolehan aplikasi pembiayaan.',
            'Sosialisasi program pemasaran, negosiasi kemitraan, dan verifikasi awal kelayakan berkas pengajuan.',
            'Analisis potensi pasar wilayah dan evaluasi produktivitas mitra kerja.',
        ],
    ],
    [
        'title'       => 'Supervisor & Sales Officer',
        'track'       => 'Non-IT',
        'org'         => 'PT Bank Woori Saudara Indonesia 1906, Tbk.',
        'date'        => 'Agu 2022 – Jan 2023',
        'location'    => 'Jakarta Selatan',
        'category'    => 'Finance & Leadership',
        'icon'        => '🏦',
        'badge'       => 'BWS',
        'logo'        => 'https://cdn.brandfetch.io/bankwoorisaudara.com/icon',
        'items'       => [
            'Mengatur strategi pemasaran produk perbankan (pembiayaan pensiunan) dan menyusun plan activity tim.',
            'Menjalin kerja sama resmi dengan instansi negara untuk kemitraan pembiayaan pensiunan.',
            'Menerapkan sistem monitoring absensi & evaluasi pencapaian target harian/bulanan tim.',
            'Melakukan survey kelayakan nasabah, collecting data, dan telemarketing.',
        ],
    ],
    [
        'title'       => 'Sales Force Pensiunan',
        'track'       => 'Non-IT',
        'org'         => 'PT Bank Syariah Indonesia Tbk (BSI)',
        'date'        => 'Mei 2022 – Jan 2023',
        'location'    => 'Cipete Selatan, Jakarta Selatan',
        'category'    => 'Finance & Sales',
        'icon'        => '🕌',
        'badge'       => 'BSI',
        'logo'        => 'https://cdn.brandfetch.io/bankbsi.co.id/icon',
        'photos'      => ['assets/experience/bsi.jpeg'],
        'items'       => [
            'Menawarkan dan mengedukasi produk pembiayaan syariah khusus pensiunan.',
            'Melakukan prospek data nasabah, telemarketing, survey lapangan, dan pengumpulan berkas administratif.',
        ],
    ],
    [
        'title'       => 'Agent Akuisisi Merchant',
        'track'       => 'Non-IT',
        'org'         => 'Ralali.com (B2B Marketplace)',
        'date'        => 'Mei 2022 – Jan 2023',
        'location'    => 'Jabodetabek',
        'category'    => 'Sales & Business',
        'icon'        => '🛒',
        'badge'       => 'Ralali',
        'logo'        => 'https://cdn.brandfetch.io/ralali.com/icon',
        'items'       => [
            'Melakukan survei lapangan dan akuisisi merchant/toko UMKM baru untuk bergabung dalam ekosistem B2B Ralali.com.',
            'Edukasi cara kerja platform digital grosir B2B kepada para pemilik usaha UMKM.',
        ],
    ],
    [
        'title'       => 'Sales Consultant',
        'track'       => 'Non-IT',
        'org'         => 'Wuling Motors (Wuling Prima Fatmawati)',
        'date'        => 'Sep 2022 – Des 2022',
        'location'    => 'Jakarta Selatan',
        'category'    => 'Sales & Business',
        'icon'        => '🚗',
        'badge'       => 'Wuling',
        'logo'        => 'https://cdn.brandfetch.io/wuling.id/icon',
        'photos'      => ['assets/experience/wuling.jpeg'],
        'items'       => [
            'Pemasaran dan penjualan unit kendaraan mobil Wuling melalui channel online dan offline.',
            'Representatif dealer dalam event & pameran otomotif serta mendampingi sesi test drive konsumen.',
        ],
    ],
    [
        'title'       => 'Surveyor - Traffic Counting & Data Collection',
        'track'       => 'Non-IT',
        'org'         => 'Sampingan (Staffinc)',
        'date'        => 'Jan 2022 – Jun 2022',
        'location'    => 'Jakarta Pusat & Jakarta Utara',
        'category'    => 'Riset & Data',
        'icon'        => '📈',
        'badge'       => 'Staffinc',
        'logo'        => 'https://cdn.brandfetch.io/staffinc.co/icon',
        'items'       => [
            'Riset dan pencatatan volume traffic driver online di titik-titik strategis menggunakan aplikasi counting digital.',
            'Menyusun laporan verifikasi data harian untuk kebutuhan riset pasar.',
        ],
    ],
    [
        'title'       => 'Data Input / Entry',
        'track'       => 'Non-IT',
        'org'         => 'Program Vaksinasi Merdeka (Polda Metro Jaya)',
        'date'        => 'Agu 2021 & Jan 2022',
        'location'    => 'Cipayung, Jakarta Timur',
        'category'    => 'Administrasi & Data',
        'icon'        => '💉',
        'badge'       => 'Polri',
        'logo'        => 'https://upload.wikimedia.org/wikipedia/commons/6/69/Logo_Polri.png',
        'photos'      => ['assets/experience/vaksinasi merdeka.jpeg'],
        'items'       => [
            'Input data registrasi penerima vaksinasi (termasuk program Vaksinasi Merdeka Anak) ke dalam database sistem pusat.',
            'Rekapitulasi berkas digital harian dengan tingkat akurasi tinggi.',
        ],
    ],
    [
        'title'       => 'Sorter (Pekerja Logistik)',
        'track'       => 'Non-IT',
        'org'         => 'Lazada Express',
        'date'        => 'Jan 2019 – Jan 2023',
        'location'    => 'Depok, Jawa Barat',
        'category'    => 'Logistik & Operasional',
        'icon'        => '📦',
        'badge'       => 'Lazada',
        'logo'        => 'https://cdn.brandfetch.io/lazada.co.id/icon',
        'items'       => [
            'Melakukan sortir, scanning barcode, dan pengelompokan paket berdasarkan zona rute distribusi kurir.',
            'Memastikan ketepatan alur sortir logistik inbound & outbound sesuai target SLA.',
        ],
    ],
    [
        'title'       => 'Teller (Staff Perbankan)',
        'track'       => 'Non-IT',
        'org'         => 'PT Bank Central Asia Tbk (BCA)',
        'date'        => 'Sep 2018 – Sep 2019',
        'location'    => 'Sunter, Jakarta Utara',
        'category'    => 'Perbankan & Finance',
        'icon'        => '🏦',
        'badge'       => 'BCA',
        'logo'        => 'https://cdn.brandfetch.io/bca.co.id/icon',
        'photos'      => ['assets/experience/bca.jpeg', 'assets/experience/bca2.jpeg'],
        'items'       => [
            'Melayani transaksi perbankan tunai dan non-tunai (setor/tarik kas, kliring, transfer, valuta asing) dengan akurasi 100%.',
            'Memberikan layanan Service Excellence berorientasi Customer Focus dan melakukan cross-selling produk perbankan.',
            'Menjalankan operasional harian sesuai kepatuhan SOP perbankan dan menyusun rekonsiliasi kas akhir hari.',
        ],
    ],
];

$trainings = [
    [
        'title'       => 'Web Developer',
        'org'         => 'Pusat Pelatihan Kerja Pengembangan Industri (PPKPI)',
        'date'        => 'Jun 2026 – Sekarang',
        'location'    => 'Jakarta, Indonesia',
        'category'    => 'Web Development',
        'icon'        => '💻',
        'badge'       => 'Sertifikat BNSP',
        'logo'        => 'assets/logo-ppkpi.jpeg',
        'tech'        => ['React.js', 'TypeScript', 'Tailwind CSS', 'JavaScript', 'Node.js', 'Vite', 'MySQL', 'Firebase'],
        'items'       => [
            'Membangun antarmuka web modern menggunakan React dalam program pelatihan pengembangan perangkat lunak.',
            'Mengembangkan aplikasi web interaktif, mengelola state komponen, serta menghubungkan frontend dengan backend/API.',
            'Menerapkan clean code, efisiensi performa, dan modern development tools.',
        ],
        'results'    => [
            ['image' => 'assets/posmart-catalog-preview.png', 'label' => 'POSMart — Storefront Neo-Bold'],
            ['image' => 'assets/posmart-products-preview.png', 'label' => 'POSMart — Manajemen Produk'],
            ['image' => 'assets/posmart-login-preview.png', 'label' => 'POSMart — Halaman Login'],
        ],
    ],
    [
        'title'       => 'Graphic Designer',
        'org'         => 'Pusat Pelatihan Kerja Pengembangan Industri (PPKPI)',
        'date'        => 'Mei 2026 – Jun 2026',
        'location'    => 'Jakarta, Indonesia',
        'category'    => 'Desain Grafis',
        'icon'        => '🎨',
        'badge'       => 'Sertifikat BNSP',
        'logo'        => 'assets/logo-ppkpi.jpeg',
        'tech'        => ['Adobe Photoshop', 'Adobe Illustrator', 'Adobe InDesign'],
        'items'       => [
            'Menguasai prinsip desain, tipografi, dan komposisi untuk menghasilkan materi visual yang estetis dan komunikatif.',
            'Menggunakan Adobe Photoshop, Adobe Illustrator, dan Adobe InDesign untuk foto, vektor, logo, ilustrasi, serta dokumen multipage.',
            'Menyelesaikan proyek branding, flyer, poster, banner, dan UI dasar untuk media cetak maupun digital.',
            'Memahami alur kerja desain dari konsep, eksekusi, hingga pre-press atau publikasi digital.',
        ],
        'results'    => [
            ['image' => 'assets/moodboard-ujk.png', 'label' => 'Moodboard UJK Desain Grafis'],
            ['image' => 'assets/hasil-flyer-ujk.png', 'label' => 'Hasil Flyer UJK Desain Grafis'],
        ],
    ],
    [
        'title'       => 'Teknisi Komputer',
        'org'         => 'Pusat Pelatihan Kerja Pengembangan Industri (PPKPI)',
        'date'        => 'Sep 2025 – Sep 2025',
        'location'    => 'Jakarta Timur',
        'category'    => 'Teknis & Hardware',
        'icon'        => '🖥️',
        'badge'       => 'PPKPI',
        'logo'        => 'assets/logo-ppkpi.jpeg',
        'items'       => [
            'Program pelatihan teknis intensif bidang Teknisi Komputer berbasis kompetensi.',
            'Menguasai perakitan, konfigurasi BIOS/UEFI, dan pemeliharaan perangkat keras (hardware) komputer.',
            'Instalasi sistem operasi, driver management, konfigurasi jaringan lokal, dan optimasi performa sistem.',
            'Melakukan analisis kerusakan (troubleshooting) perangkat keras/lunak dan perbaikan sesuai standar teknis.',
        ],
        'results'    => [
            ['image' => 'assets/experience/activity-teknisi-komputer.jpeg', 'label' => 'Kegiatan Pelatihan Teknisi Komputer'],
        ],
    ],
    [
        'title'       => 'Computer Operator',
        'org'         => 'Pusat Pelatihan Kerja Pengembangan Industri (PPKPI)',
        'date'        => 'Okt 2024 – Nov 2024',
        'location'    => 'Cipayung, Jakarta',
        'category'    => 'Teknis & Data',
        'icon'        => '📊',
        'badge'       => 'PPKPI',
        'logo'        => 'assets/logo-ppkpi.jpeg',
        'tech'        => ['Microsoft Office', 'Excel'],
        'items'       => [
            'Program pelatihan vokasi & kompetensi bidang Operator Komputer.',
            'Pengoperasian Office Suite tingkat lanjut untuk kebutuhan administrasi, analisa lembar kerja data, dan laporan profesional.',
            'Manajemen sistem komputer, pengelolaan file digital terstruktur, dan pemeliharaan sistem pendukung produktivitas.',
        ],
        'results'    => [
            ['image' => 'assets/experience/activity-operator-komputer.jpeg', 'label' => 'Kegiatan Operator Komputer'],
            ['image' => 'assets/experience/activity-operator-komputer-2.jpeg', 'label' => 'Kegiatan Operator Komputer (2)'],
        ],
    ],
];

$stats = [

    ['num' => 'HKI', 'label' => 'Hak Cipta Resmi', 'sub' => 'Kemenkumham DJKI'],
    ['num' => '13+', 'label' => 'Riwayat Karir', 'sub' => 'Teknis & Manajerial'],

];

$skills = [
    ['icon' => '🌐', 'title' => 'Web Front-end', 'desc' => 'React, TypeScript, Next.js, Tailwind, HTML, CSS, JavaScript'],
    ['icon' => '🗄️', 'title' => 'Backend & DB', 'desc' => 'Laravel (PHP), Node.js, MySQL, Firebase'],
    ['icon' => '📱', 'title' => 'Mobile Development', 'desc' => 'Flutter, Dart, Kotlin (Android Studio)'],
    ['icon' => '🧰', 'title' => 'Tools & DevOps', 'desc' => 'Git, GitHub, Docker, Postman, VS Code, Figma'],
    ['icon' => '🎨', 'title' => 'Graphic Design & Office', 'desc' => 'Adobe Photoshop, Illustrator, InDesign, Microsoft Office'],
    ['icon' => '🛠️', 'title' => 'Hardware & Service', 'desc' => 'Troubleshooting Komputer, Maintenance Mesin EDC, Repair Gadget'],
    ['icon' => '👥', 'title' => 'Leadership & Team', 'desc' => 'Person In Charge (PIC), Team Leader, Supervisi Tim & Lapangan'],
    ['icon' => '💼', 'title' => 'Bisnis & Perbankan', 'desc' => 'Perbankan (BCA Teller), Akuisisi Merchant B2B, Field Marketing'],
];

$techSkillPills = [
    ['name' => 'Laravel', 'category' => 'Backend', 'icon' => 'laravel', 'color' => '#f55247'],
    ['name' => 'PHP', 'category' => 'Backend', 'icon' => 'php', 'color' => '#777bb4'],
    ['name' => 'React.js', 'category' => 'Frontend', 'icon' => 'react', 'color' => '#61dafb'],
    ['name' => 'Next.js', 'category' => 'Frontend', 'icon' => 'next', 'color' => '#ffffff'],
    ['name' => 'TypeScript', 'category' => 'Frontend', 'icon' => 'ts', 'color' => '#3178c6'],
    ['name' => 'JavaScript', 'category' => 'Frontend', 'icon' => 'javascript', 'color' => '#f7df1e'],
    ['name' => 'HTML5', 'category' => 'Frontend', 'icon' => 'html', 'color' => '#e34f26'],
    ['name' => 'CSS3', 'category' => 'Frontend', 'icon' => 'css', 'color' => '#1572b6'],
    ['name' => 'TailwindCSS', 'category' => 'Frontend', 'icon' => 'tailwind', 'color' => '#38bdf8'],
    ['name' => 'Bootstrap', 'category' => 'Frontend', 'icon' => 'bootstrap', 'color' => '#7952b3'],
    ['name' => 'Flutter', 'category' => 'Mobile', 'icon' => 'flutter', 'color' => '#02569b'],
    ['name' => 'Kotlin', 'category' => 'Mobile', 'icon' => 'kotlin', 'color' => '#7f52ff'],
    ['name' => 'Android', 'category' => 'Mobile', 'icon' => 'android', 'color' => '#3ddc84'],
    ['name' => 'MySQL', 'category' => 'Backend', 'icon' => 'mysql', 'color' => '#4479a1'],
    ['name' => 'Firebase', 'category' => 'Backend', 'icon' => 'firebase', 'color' => '#ffca28'],
    ['name' => 'Git & GitHub', 'category' => 'Tools', 'icon' => 'git', 'color' => '#f05032'],
    ['name' => 'Docker', 'category' => 'Tools', 'icon' => 'docker', 'color' => '#2496ed'],
    ['name' => 'Postman', 'category' => 'Tools', 'icon' => 'postman', 'color' => '#ff6c37'],
    ['name' => 'Figma', 'category' => 'Tools', 'icon' => 'figma', 'color' => '#f24e1e'],
    ['name' => 'VS Code', 'category' => 'Tools', 'icon' => 'vscode', 'color' => '#007acc'],
    ['name' => 'Microsoft Office', 'category' => 'Tools', 'icon' => 'microsoftoffice', 'local_icon' => 'assets/microsoft-office.svg', 'mark' => 'MS', 'color' => '#f25022'],
    ['name' => 'Adobe Photoshop', 'category' => 'Tools', 'icon' => 'ps', 'color' => '#31a8ff'],
    ['name' => 'Adobe Illustrator', 'category' => 'Tools', 'icon' => 'ai', 'color' => '#ff9a00'],
    ['name' => 'Adobe InDesign', 'category' => 'Tools', 'icon' => 'id', 'local_icon' => 'assets/adobe-indesign.svg', 'mark' => 'Id', 'color' => '#ff3366'],
];

$techIcons = ['laravel','react','php','flutter','firebase','html','css','javascript','mysql','git','docker','ts','next','tailwind','kotlin'];

$certificates = [
    [
        'title' => 'The Role Of CLO as a Strategic Partner',
        'category' => 'Non-IT',
        'issuer' => 'QuBisa',
        'date' => '17 Februari 2022',
        'credential' => '2U13QBTZ5YOU7H',
        'image' => 'assets/strategic-partner.jpg',
        'file' => 'assets/strategic-partner.jpg',
    ],
    [
        'title' => 'Menjadi Marketer Tangguh Sesuai Kebutuhan Pasar',
        'category' => 'Non-IT',
        'issuer' => 'QuBisa',
        'date' => '14 Februari 2022',
        'credential' => '5NQKDVRENBJBOV',
        'image' => 'assets/marketer-tangguh.jpg',
        'file' => 'assets/marketer-tangguh.jpg',
    ],
    [
        'title' => 'Pentingnya Penguasaan Digital Di Era Disrupsi',
        'category' => 'IT',
        'issuer' => 'QuBisa',
        'date' => '19 Februari 2022',
        'credential' => 'G9X4DC0RTJQ9KW',
        'image' => 'assets/penguasaan-digital.jpg',
        'file' => 'assets/penguasaan-digital.jpg',
    ],
    [
        'title' => 'Berubah Atau Punah',
        'category' => 'Non-IT',
        'issuer' => 'QuBisa',
        'date' => '16 Februari 2022',
        'credential' => 'GS2DKUXL5371ML',
        'image' => 'assets/berubah-atau-punah.jpg',
        'file' => 'assets/berubah-atau-punah.jpg',
    ],
    [
        'title' => 'Komunikasi Tanpa Sensi',
        'category' => 'Non-IT',
        'issuer' => 'QuBisa',
        'date' => '18 Februari 2022',
        'credential' => 'QWY91MWP2QIBMW',
        'image' => 'assets/komunikasi-tanpa-sensi.jpg',
        'file' => 'assets/komunikasi-tanpa-sensi.jpg',
    ],
    [
        'title' => 'The Teenagers Character Building Program — Roadmap to Success',
        'category' => 'Non-IT',
        'issuer' => 'Bank Mayora / James Gwee Dream Achievers',
        'date' => '13–14 Agustus 2016',
        'credential' => null,
        'image' => 'assets/roadmap-to-success.webp',
        'file' => 'assets/roadmap-to-success.jpg',
    ],
    [
        'title' => 'Anti Fraud',
        'category' => 'Non-IT',
        'issuer' => 'Sertifikat Pelatihan',
        'date' => null,
        'credential' => null,
        'image' => 'assets/anti-fraud-preview.png',
        'file' => 'assets/anti-fraud.pdf',
    ],
    [
        'title' => 'API',
        'category' => 'IT',
        'issuer' => 'Sertifikat Pelatihan',
        'date' => null,
        'credential' => null,
        'image' => 'assets/api-preview.png',
        'file' => 'assets/api.pdf',
    ],
    [
        'title' => 'Cyber Security',
        'category' => 'IT',
        'issuer' => 'Sertifikat Pelatihan',
        'date' => null,
        'credential' => null,
        'image' => 'assets/cyber-security-preview.png',
        'file' => 'assets/cyber-security.pdf',
    ],
    [
        'title' => 'Digital Transformation Era',
        'category' => 'IT',
        'issuer' => 'Sertifikat Pelatihan',
        'date' => null,
        'credential' => null,
        'image' => 'assets/digital-transformation-era-preview.webp',
        'file' => 'assets/digital-transformation-era.pdf',
    ],
    [
        'title' => 'Perilaku di BCA',
        'category' => 'Non-IT',
        'issuer' => 'BCA',
        'date' => null,
        'credential' => null,
        'image' => 'assets/perilaku-di-bca-preview.png',
        'file' => 'assets/perilaku-di-bca.pdf',
    ],
    [
        'title' => 'Piagam Penghargaan Reynaldi Delphiano',
        'category' => 'Non-IT',
        'issuer' => 'Piagam Penghargaan',
        'date' => null,
        'credential' => null,
        'image' => 'assets/piagam-penghargaan-reynaldi-delphiano-preview.webp',
        'file' => 'assets/piagam-penghargaan-reynaldi-delphiano.pdf',
    ],
    [
        'title' => 'Sertifikat Excel',
        'category' => 'IT',
        'issuer' => 'Fasz Edu',
        'date' => '8–10 Februari 2022',
        'credential' => '75/faszedu/OSMM-40/II/2022',
        'image' => 'assets/sertifikat-excel-preview.png',
        'file' => 'assets/sertifikat-excel.pdf',
    ],
    [
        'title' => 'UX Writing',
        'category' => 'IT',
        'issuer' => 'Loker Programmer',
        'date' => '12 Februari 2022',
        'credential' => '0035/ITUW/PST/LOKPRO/II/2022',
        'image' => 'assets/loker-programmer-ux-writing-preview.webp',
        'file' => 'assets/loker-programmer-ux-writing.pdf',
    ],
    [
        'title' => 'Web Developer: The Art of Our Web',
        'category' => 'IT',
        'issuer' => 'Loker Programmer',
        'date' => '5 Februari 2022',
        'credential' => '0034/WDTAOW/PST/LOKPRO/II/2022',
        'image' => 'assets/loker-programmer-web-developer-preview.webp',
        'file' => 'assets/loker-programmer-web-developer.pdf',
    ],
    [
        'title' => 'Vaksinasi Merdeka Anak',
        'category' => 'Non-IT',
        'issuer' => 'Program Vaksinasi Merdeka Anak',
        'date' => null,
        'credential' => null,
        'image' => 'assets/sertifikat-vm-anak-reynaldi-delphiano-preview.webp',
        'file' => 'assets/sertifikat-vm-anak-reynaldi-delphiano.pdf',
    ],
];

