<?php
// ============================================================
// DATA PORTOFOLIO — edit cukup di file ini, halaman otomatis update
// ============================================================

$googleAnalyticsId = 'G-DPC3HR787T';

$profile = [
    'name'          => 'Reynaldi Delphiano',
    'brand'         => 'ReyDel',
    'initial'       => 'RD',
    'eyebrow'       => 'Halo, saya',
    'role'          => 'Web & Mobile Developer',
    'role2'         => 'Pengembang Aplikasi',
    'location'      => 'Jakarta, Indonesia',
    'languages'     => 'Indonesia (Native), Inggris (Limited Working)',
    'focus'         => 'Web Development, Mobile Apps, UMKM Digital',
    'email'         => 'delphianor@gmail.com',
    'linkedin_url'  => 'https://www.linkedin.com/in/reynaldi-delphiano-2b6b79120',
    'linkedin_name' => 'reynaldi-delphiano',
    'social'        => [
        ['label' => 'Email',       'handle' => 'delphianor@gmail.com',  'url' => 'mailto:delphianor@gmail.com'],
        ['label' => 'WhatsApp',    'handle' => '085155376508',           'url' => 'https://wa.me/6285155376508'],
        ['label' => 'LinkedIn',    'handle' => 'Reynaldi Delphiano',     'url' => 'https://www.linkedin.com/in/reynaldi-delphiano-2b6b79120'],
        ['label' => 'Instagram',   'handle' => '@reynaldi_delphiano_',   'url' => 'https://instagram.com/reynaldi_delphiano'],
        ['label' => 'TikTok',      'handle' => '@rajajasa7',             'url' => 'https://www.tiktok.com/@rajajasa7/'],
        ['label' => 'YouTube',     'handle' => '@reynaldidelphiano5684', 'url' => 'https://www.youtube.com/@reynaldidelphiano5684'],
        ['label' => 'GitHub',      'handle' => 'ReyDel6',                'url' => 'https://github.com/ReyDel6'],
    ],
    'photo'         => 'assets/foto.jpeg',
    'photo_avatar'  => 'assets/foto-pixel.jpg',
    'summary'       => [
        'Saya seorang <strong>Web & Mobile Developer</strong> yang berfokus membangun aplikasi web dan mobile yang fungsional, responsif, serta mudah digunakan. Saya terbiasa menggunakan Laravel/PHP, React, JavaScript, Flutter, MySQL, dan REST API untuk mengubah kebutuhan menjadi solusi digital.',
        'Salah satu proyek yang saya kembangkan adalah <strong>UMKM Connect</strong>, platform digital yang menggabungkan fitur Kasir/POS, QR Meja, dan B2B antar-UMKM. Proyek ini saya bangun untuk membantu pelaku UMKM mengelola transaksi, menerima pesanan, dan terhubung dengan mitra usaha secara lebih praktis.',
        'Dalam mengembangkan aplikasi, saya berkomitmen menerapkan clean code, integrasi REST API, dan workflow modern agar setiap solusi yang dibangun tetap rapi, efisien, mudah dikembangkan, dan sesuai dengan kebutuhan pengguna.',
        'Di luar bidang teknologi, saya memiliki pengalaman profesional lintas bidang, mulai dari penjualan, operasional, perbankan, layanan teknis, hingga kepemimpinan tim. Pengalaman tersebut membentuk kemampuan komunikasi, koordinasi, problem solving, ketelitian, dan adaptasi yang saya terapkan dalam setiap proyek.',
    ],
];

$projects = [
    [
        'title'    => 'UMKM Connect',
        'tag'      => 'Karya Pribadi • Fullstack',
        'badge'    => 'Hak Cipta Terdaftar',
        'image'    => 'assets/umkm-connect.png',
        'initial'  => 'UMKM Connect',
        'github'   => 'https://github.com/ReyDel6/UMKM_Connect-Web',
        'desc'     => 'Platform web untuk UMKM yang memadukan <strong>Kasir/POS</strong>, <strong>QR Meja</strong> (pesan & bayar dari meja pelanggan), dan <strong>B2B antar-UMKM</strong> dalam satu akun.',
        'points'   => [
            '<strong>Marketplace B2B</strong> — toko online antar-UMKM dengan keranjang & checkout grosir.',
            '<strong>Pesan via QR Meja</strong> — pelanggan scan QR, lihat menu, pesan & bayar online dari smartphone.',
            '<strong>Kasir (POS)</strong> — dashboard, manajemen shift, pesanan meja, & ID card digital kasir.',
            '<strong>Manajemen Karyawan</strong> — tambah kasir, koki, pelayan, barista, admin (login via PIN 4 digit).',
            '<strong>Chat antar-pengguna</strong> — komunikasi langsung pembeli & penjual.',
            '<strong>Produk & Stok</strong>, bahan baku, pesanan masuk, & laporan keuangan.',
            '<strong>Multi-role & autentikasi</strong> — Owner, Admin, Cashier, Supplier, Customer; login email, Google, & reset password.',
            '<strong>Pembayaran Midtrans</strong> (Snap) & landing page dengan form hubungi kami.',
        ],
        'meta'     => 'Teknologi: <strong>Laravel (PHP)</strong>, Blade + Vite, MySQL • Pembayaran <strong>Midtrans</strong> • Terdaftar Hak Cipta <strong>EC002026133137</strong> (2026)',
        'tech'     => [
            'Backend: Laravel (PHP)',
            'Frontend: Blade + Vite, Font Awesome, GSAP',
            'Database: MySQL',
            'Pembayaran: Midtrans Snap API',
        ],
        'roles'    => [
            'Owner/UMKM — kelola penuh produk, stok, karyawan, laporan.',
            'Admin — membantu owner dalam operasional toko.',
            'Cashier — kasir (POS), pesanan meja, profil kasir.',
            'Supplier — setara UMKM; produknya tampil di marketplace.',
            'Customer — akun scan QR meja & pembayaran online dengan dashboard & riwayat order sendiri.',
        ],
        'hki'      => 'Proyek <strong>UMKM Connect</strong> — termasuk source code, desain antarmuka, logo, dan fitur — adalah karya orisinal milik <strong>Reynaldi Delphiano</strong>, dilindungi Hak Cipta dan dicatatkan di DJKI (HKI <strong>EC002026133137</strong>, 2026). Dilarang menggandakan, mendistribusikan, atau mengomersialkan tanpa izin tertulis pemegang hak.',
        'previews' => [
            ['file' => 'assets/umkm-web-marketplace-preview.png', 'label' => 'Marketplace B2B UMKM'],
            ['file' => 'assets/umkm-web-login-preview.png', 'label' => 'Halaman Login'],
        ],
    ],
    [
        'title'    => 'POSMart',
        'tag'      => 'Karya Pribadi • Fullstack',
        'badge'    => 'Point of Sale',
        'image'    => 'assets/posmart-preview.svg',
        'initial'  => 'POSMart',
        'github'   => 'https://github.com/ReyDel6/POSMART',
        'desc'     => 'Aplikasi <strong>Point of Sale (POS)</strong> berbasis web untuk manajemen penjualan, produk, stok, dan laporan — dengan dashboard multi-role (Admin, Kasir, Owner) dan login Google.',
        'points'   => [
            '<strong>Dashboard multi-role</strong> — Admin (kelola pengguna & produk), Kasir (transaksi POS cepat), Owner (laporan & rekap penjualan).',
            '<strong>Kasir modern</strong> — katalog produk, keranjang belanja, diskon, dan proses checkout cepat.',
            '<strong>Manajemen produk &amp; stok</strong> — tambah/ubah produk, kategori, harga, dan stok secara real-time.',
            '<strong>Autentikasi Google</strong> — login cepat dengan akun Google selain email & password.',
            '<strong>Ringkasan penjualan</strong> — kartu statistik dan laporan rekap per periode.',
        ],
        'meta'     => 'Teknologi: <strong>React + Vite + Tailwind (Frontend)</strong> • <strong>Laravel (PHP API Backend)</strong> • SQLite • Integrasi Google OAuth • Laporan',
        'tech'     => [
            'Frontend: React.js + Vite, Tailwind CSS, Material Tailwind',
            'Backend: Laravel (PHP) — REST API',
            'Database: SQLite',
            'Auth: Email/Password + Google OAuth',
        ],
        'roles'    => [
            'Admin — kelola pengguna, produk, dan data master.',
            'Kasir — transaksi penjualan cepat melalui antarmuka POS.',
            'Owner — melihat laporan penjualan & rekap usaha.',
        ],
        'previews' => [
            ['file' => 'assets/posmart-dashboard-preview.png', 'label' => 'Dashboard Admin'],
            ['file' => 'assets/posmart-catalog-preview.png', 'label' => 'Katalog Produk & Kasir'],
            ['file' => 'assets/posmart-products-preview.png', 'label' => 'Manajemen Produk'],
            ['file' => 'assets/posmart-login-preview.png', 'label' => 'Halaman Login'],
        ],
    ],
    [
        'title'    => 'Website Portfolio Reynaldi Delphiano',
        'tag'      => 'Karya Pribadi • Reynaldi Delphiano',
        'badge'    => 'Personal Web',
        'image'    => 'assets/portfolio-preview.svg',
        'initial'  => 'RD Portfolio',
        'github'   => 'https://github.com/ReyDel6/ReyPortofolio',
        'live'     => 'http://reydel.page.gd/',
        'desc'     => 'Website personal milik <strong>Reynaldi Delphiano</strong> untuk menampilkan profil profesional, pengalaman kerja, pendidikan, skill, proyek, dan sertifikasi dalam satu halaman yang responsif.',
        'points'   => [
            '<strong>Profil profesional</strong> — ringkasan diri, fokus pengembangan, dan kontak sosial media.',
            '<strong>Showcase proyek</strong> — menampilkan UMKM Connect beserta fitur dan dokumentasinya.',
            '<strong>Lisensi & sertifikasi</strong> — galeri gambar sertifikat dan link PDF yang dapat dibuka.',
            '<strong>Responsive design</strong> — tampilan menyesuaikan desktop, tablet, dan mobile.',
        ],
        'meta'     => 'Teknologi: <strong>PHP</strong>, HTML, CSS, JavaScript • Data terpusat di <strong>data.php</strong>',
        'tech'     => [
            'Backend: PHP',
            'Frontend: HTML, CSS, JavaScript',
            'UI: Responsive design',
            'Deployment: InfinityFree-ready',
        ],
        'preview'       => 'assets/portfolio-home-preview.png',
        'preview_label' => 'Preview Website',
    ],
    [
        'title'    => 'UMKM Connect Mobile',
        'tag'      => 'Karya Pribadi • Mobile Development',
        'badge'    => 'Flutter Mobile App',
        'image'    => 'assets/umkm-connect-mobile.svg',
        'initial'  => 'UMKM Connect Mobile',
        'desc'     => 'Versi mobile <strong>UMKM Connect</strong> berbasis Flutter untuk membantu UMKM mengelola operasional, katalog, stok, transaksi, laporan, serta koneksi dengan customer dan supplier melalui smartphone.',
        'points'   => [
            '<strong>Aplikasi cross-platform</strong> — dikembangkan dengan Flutter dan Dart untuk pengalaman mobile yang konsisten.',
            '<strong>Dashboard & laporan</strong> — memantau produk, stok, transaksi, dan ringkasan penjualan dari perangkat mobile.',
            '<strong>Multi-role</strong> — mendukung alur Owner/UMKM, Supplier, dan Customer dengan akses sesuai kebutuhan.',
            '<strong>Customer & Supplier</strong> — menu pelanggan via QR, pencarian supplier, pemesanan, dan komunikasi antar-pengguna.',
            '<strong>Firebase terintegrasi</strong> — autentikasi, database Firestore, dan penyimpanan file melalui Firebase Storage.',
        ],
        'meta'     => 'Teknologi: <strong>Flutter (Dart)</strong> • Firebase Auth, Firestore, Storage • QR & laporan data',
        'tech'     => [
            'Mobile: Flutter + Dart',
            'Backend: Firebase Auth + Firestore',
            'Storage: Firebase Storage',
            'Utilities: QR, Chart, HTTP, Notifications',
        ],
        'hki'      => 'Proyek <strong>UMKM Connect</strong> beserta source code, desain antarmuka, logo, dan fiturnya adalah karya orisinal milik <strong>Reynaldi Delphiano</strong>, dilindungi Hak Cipta dan dicatatkan di DJKI (HKI <strong>EC002026133137</strong>, 2026).',
        'uiux'     => 'assets/ui-ux-umkm.jpeg',
        'uiux_label'=> 'Desain UI/UX Mobile',
        'hki_image'=> 'assets/haki-umkm.jpeg',
        'certificate' => [
            'label'  => 'Sertifikat Juara',
            'file'   => 'assets/sertifikat-juara.pdf',
        ],
        'download' => [
            'label' => 'Unduh APK Android',
            'file'  => 'https://github.com/ReyDel6/UMKM_Connect-Web/releases',
        ],
    ],
];

$education = [
    [
        'degree'   => 'S1 Sistem Informasi',
        'school'   => 'Universitas Bina Sarana Informatika (BSI)',
        'date'     => 'Mar 2024 – Mar 2028 (Diharapkan)',
        'icon'     => '🎓',
        'badge'    => 'UBSI',
        'logo'     => 'https://cdn.brandfetch.io/bsi.ac.id/icon',
        'desc'     => 'Mempelajari arsitektur sistem informasi, rekayasa perangkat lunak, manajemen basis data, dan pengembangan aplikasi enterprise.',
    ],
];

$experiences = [
    [
        'title'       => 'PIC (Person In Charge)',
        'track'       => 'Non-IT',
        'org'         => 'PT Hasta Ayu Nusantara',
        'date'        => 'Jan 2026 – Jun 2026',
        'location'    => 'Jakarta, Indonesia',
        'category'    => 'Leadership & Ops',
        'icon'        => '🏢',
        'badge'       => 'HAN',
        'logo'        => 'https://images.glints.com/unsafe/glints-dashboard.s3.amazonaws.com/company-logo/e3599d10e533038cf5697241dc2851cf.png',
        'items'       => [
            'Bertanggung jawab penuh mengelola operasional harian, koordinasi tim lintas fungsi, dan memastikan pencapaian target proyek sesuai standar perusahaan.',
            'Memimpin, mengarahkan, dan mengevaluasi kinerja anggota tim guna meningkatkan produktivitas serta efisiensi kerja di lapangan.',
            'Menjadi point of contact utama lintas divisi serta menangani problem solving operasional secara taktis.',
            'Mengelola administrasi proyek, penyusunan laporan berkala, dan kepatuhan SOP operasional.',
        ],
    ],
    [
        'title'       => 'Team Leader',
        'track'       => 'Non-IT',
        'org'         => 'Colony Group of Companies (Nescafé)',
        'date'        => 'Jul 2025 – Des 2025',
        'location'    => 'Pasar Minggu, Jakarta',
        'category'    => 'Leadership & Sales',
        'icon'        => '☕',
        'badge'       => 'Nescafé',
        'logo'        => 'https://cdn.brandfetch.io/nescafe.com/icon',
        'items'       => [
            'Memimpin dan mengawasi kinerja tim field sales / promoter untuk target penjualan produk Nescafé (harian, mingguan, bulanan).',
            'Mengkoordinasikan event, pameran, dan kegiatan brand activation di lapangan guna meningkatkan penetrasi pasar & brand awareness.',
            'Melakukan briefing rutin, evaluasi performa kerja, dan pelatihan strategi penjualan tim.',
            'Menyusun sales report berkala, menganalisis tren pasar, dan memberikan rekomendasi taktis ke manajemen.',
        ],
    ],
    [
        'title'       => 'Service Technician (Mesin EDC)',
        'track'       => 'IT',
        'org'         => 'PT Bank Central Asia Tbk (BCA)',
        'date'        => 'Sep 2024 – Okt 2024',
        'location'    => 'Kebon Jeruk, Jakarta',
        'category'    => 'Teknis & Hardware',
        'icon'        => '🏦',
        'badge'       => 'BCA',
        'logo'        => 'https://cdn.brandfetch.io/bca.co.id/icon',
        'items'       => [
            'Melakukan maintenance berkala, perbaikan, installment (pemasangan baru), dan replace mesin EDC di berbagai merchant BCA.',
            'Memastikan konektivitas jaringan terminal EDC dan kelancaran transaksi merchant.',
        ],
    ],
    [
        'title'       => 'Service Technician (Smartphone & Gadget)',
        'track'       => 'IT',
        'org'         => 'Laku6.com',
        'date'        => 'Apr 2024 – Sep 2024',
        'location'    => 'Cengkareng, Jakarta',
        'category'    => 'Teknis & Hardware',
        'icon'        => '📱',
        'badge'       => 'Laku6',
        'logo'        => 'https://cdn.brandfetch.io/laku6.com/icon',
        'items'       => [
            'Melakukan QC & feature testing mendalam pada smartphone untuk kelayakan fungsi jual-beli kembali.',
            'Melakukan pergantian dan repair sparepart hardware handphone.',
            'Troubleshooting dan penyelesaian masalah software (OS Android & iOS flashing/reset).',
        ],
    ],
    [
        'title'       => 'Marketing Agent Officer',
        'track'       => 'Non-IT',
        'org'         => 'WOM Finance',
        'date'        => 'Jan 2023 – Mar 2023',
        'location'    => 'Jakarta Selatan',
        'category'    => 'Finance & Marketing',
        'icon'        => '💳',
        'badge'       => 'WOM',
        'logo'        => 'https://cdn.brandfetch.io/wom.co.id/icon',
        'items'       => [
            'Mengelola, mengembangkan, dan memperluas jaringan kemitraan agen untuk meningkatkan perolehan aplikasi pembiayaan.',
            'Sosialisasi program pemasaran, negosiasi kemitraan, dan verifikasi awal kelayakan berkas pengajuan.',
            'Analisis potensi pasar wilayah dan evaluasi produktivitas mitra kerja.',
        ],
    ],
    [
        'title'       => 'Supervisor & Sales Officer',
        'track'       => 'Non-IT',
        'org'         => 'PT Bank Woori Saudara Indonesia 1906, Tbk.',
        'date'        => 'Agu 2022 – Jan 2023',
        'location'    => 'Jakarta Selatan',
        'category'    => 'Finance & Leadership',
        'icon'        => '🏦',
        'badge'       => 'BWS',
        'logo'        => 'https://cdn.brandfetch.io/bankwoorisaudara.com/icon',
        'items'       => [
            'Mengatur strategi pemasaran produk perbankan (pembiayaan pensiunan) dan menyusun plan activity tim.',
            'Menjalin kerja sama resmi dengan instansi negara untuk kemitraan pembiayaan pensiunan.',
            'Menerapkan sistem monitoring absensi & evaluasi pencapaian target harian/bulanan tim.',
            'Melakukan survey kelayakan nasabah, collecting data, dan telemarketing.',
        ],
    ],
    [
        'title'       => 'Sales Force Pensiunan',
        'track'       => 'Non-IT',
        'org'         => 'PT Bank Syariah Indonesia Tbk (BSI)',
        'date'        => 'Mei 2022 – Jan 2023',
        'location'    => 'Cipete Selatan, Jakarta Selatan',
        'category'    => 'Finance & Sales',
        'icon'        => '🕌',
        'badge'       => 'BSI',
        'logo'        => 'https://cdn.brandfetch.io/bankbsi.co.id/icon',
        'photos'      => ['assets/experience/bsi.jpeg'],
        'items'       => [
            'Menawarkan dan mengedukasi produk pembiayaan syariah khusus pensiunan.',
            'Melakukan prospek data nasabah, telemarketing, survey lapangan, dan pengumpulan berkas administratif.',
        ],
    ],
    [
        'title'       => 'Agent Akuisisi Merchant',
        'track'       => 'Non-IT',
        'org'         => 'Ralali.com (B2B Marketplace)',
        'date'        => 'Mei 2022 – Jan 2023',
        'location'    => 'Jabodetabek',
        'category'    => 'Sales & Business',
        'icon'        => '🛒',
        'badge'       => 'Ralali',
        'logo'        => 'https://cdn.brandfetch.io/ralali.com/icon',
        'items'       => [
            'Melakukan survei lapangan dan akuisisi merchant/toko UMKM baru untuk bergabung dalam ekosistem B2B Ralali.com.',
            'Edukasi cara kerja platform digital grosir B2B kepada para pemilik usaha UMKM.',
        ],
    ],
    [
        'title'       => 'Sales Consultant',
        'track'       => 'Non-IT',
        'org'         => 'Wuling Motors (Wuling Prima Fatmawati)',
        'date'        => 'Sep 2022 – Des 2022',
        'location'    => 'Jakarta Selatan',
        'category'    => 'Sales & Business',
        'icon'        => '🚗',
        'badge'       => 'Wuling',
        'logo'        => 'https://cdn.brandfetch.io/wuling.id/icon',
        'photos'      => ['assets/experience/wuling.jpeg'],
        'items'       => [
            'Pemasaran dan penjualan unit kendaraan mobil Wuling melalui channel online dan offline.',
            'Representatif dealer dalam event & pameran otomotif serta mendampingi sesi test drive konsumen.',
        ],
    ],
    [
        'title'       => 'Surveyor - Traffic Counting & Data Collection',
        'track'       => 'Non-IT',
        'org'         => 'Sampingan (Staffinc)',
        'date'        => 'Jan 2022 – Jun 2022',
        'location'    => 'Jakarta Pusat & Jakarta Utara',
        'category'    => 'Riset & Data',
        'icon'        => '📈',
        'badge'       => 'Staffinc',
        'logo'        => 'https://cdn.brandfetch.io/staffinc.co/icon',
        'items'       => [
            'Riset dan pencatatan volume traffic driver online di titik-titik strategis menggunakan aplikasi counting digital.',
            'Menyusun laporan verifikasi data harian untuk kebutuhan riset pasar.',
        ],
    ],
    [
        'title'       => 'Data Input / Entry',
        'track'       => 'Non-IT',
        'org'         => 'Program Vaksinasi Merdeka (Polda Metro Jaya)',
        'date'        => 'Agu 2021 & Jan 2022',
        'location'    => 'Cipayung, Jakarta Timur',
        'category'    => 'Administrasi & Data',
        'icon'        => '💉',
        'badge'       => 'Polri',
        'logo'        => 'https://upload.wikimedia.org/wikipedia/commons/6/69/Logo_Polri.png',
        'photos'      => ['assets/experience/vaksinasi merdeka.jpeg'],
        'items'       => [
            'Input data registrasi penerima vaksinasi (termasuk program Vaksinasi Merdeka Anak) ke dalam database sistem pusat.',
            'Rekapitulasi berkas digital harian dengan tingkat akurasi tinggi.',
        ],
    ],
    [
        'title'       => 'Sorter (Pekerja Logistik)',
        'track'       => 'Non-IT',
        'org'         => 'Lazada Express',
        'date'        => 'Jan 2019 – Jan 2023',
        'location'    => 'Depok, Jawa Barat',
        'category'    => 'Logistik & Operasional',
        'icon'        => '📦',
        'badge'       => 'Lazada',
        'logo'        => 'https://cdn.brandfetch.io/lazada.co.id/icon',
        'items'       => [
            'Melakukan sortir, scanning barcode, dan pengelompokan paket berdasarkan zona rute distribusi kurir.',
            'Memastikan ketepatan alur sortir logistik inbound & outbound sesuai target SLA.',
        ],
    ],
    [
        'title'       => 'Teller (Staff Perbankan)',
        'track'       => 'Non-IT',
        'org'         => 'PT Bank Central Asia Tbk (BCA)',
        'date'        => 'Sep 2018 – Sep 2019',
        'location'    => 'Sunter, Jakarta Utara',
        'category'    => 'Perbankan & Finance',
        'icon'        => '🏦',
        'badge'       => 'BCA',
        'logo'        => 'https://cdn.brandfetch.io/bca.co.id/icon',
        'photos'      => ['assets/experience/bca.jpeg', 'assets/experience/bca2.jpeg'],
        'items'       => [
            'Melayani transaksi perbankan tunai dan non-tunai (setor/tarik kas, kliring, transfer, valuta asing) dengan akurasi 100%.',
            'Memberikan layanan Service Excellence berorientasi Customer Focus dan melakukan cross-selling produk perbankan.',
            'Menjalankan operasional harian sesuai kepatuhan SOP perbankan dan menyusun rekonsiliasi kas akhir hari.',
        ],
    ],
];

$trainings = [
    [
        'title'       => 'Web Developer',
        'org'         => 'Pusat Pelatihan Kerja Pengembangan Industri (PPKPI)',
        'date'        => 'Jun 2026 – Sekarang',
        'location'    => 'Jakarta, Indonesia',
        'category'    => 'Web Development',
        'icon'        => '💻',
        'badge'       => 'Sertifikat BNSP',
        'logo'        => 'assets/logo-ppkpi.jpeg',
        'items'       => [
            'Membangun antarmuka web modern menggunakan React dalam program pelatihan pengembangan perangkat lunak.',
            'Mengembangkan aplikasi web interaktif, mengelola state komponen, serta menghubungkan frontend dengan backend/API.',
            'Menerapkan clean code, efisiensi performa, dan modern development tools.',
        ],
    ],
    [
        'title'       => 'Graphic Designer',
        'org'         => 'Pusat Pelatihan Kerja Pengembangan Industri (PPKPI)',
        'date'        => 'Mei 2026 – Jun 2026',
        'location'    => 'Jakarta, Indonesia',
        'category'    => 'Desain Grafis',
        'icon'        => '🎨',
        'badge'       => 'Sertifikat BNSP',
        'logo'        => 'assets/logo-ppkpi.jpeg',
        'items'       => [
            'Menguasai prinsip desain, tipografi, dan komposisi untuk menghasilkan materi visual yang estetis dan komunikatif.',
            'Menggunakan Adobe Photoshop, Adobe Illustrator, dan Adobe InDesign untuk foto, vektor, logo, ilustrasi, serta dokumen multipage.',
            'Menyelesaikan proyek branding, flyer, poster, banner, dan UI dasar untuk media cetak maupun digital.',
            'Memahami alur kerja desain dari konsep, eksekusi, hingga pre-press atau publikasi digital.',
        ],
    ],
    [
        'title'       => 'Teknisi Komputer',
        'org'         => 'Pusat Pelatihan Kerja Pengembangan Industri (PPKPI)',
        'date'        => 'Sep 2025 – Sep 2025',
        'location'    => 'Jakarta Timur',
        'category'    => 'Teknis & Hardware',
        'icon'        => '🖥️',
        'badge'       => 'PPKPI',
        'logo'        => 'assets/logo-ppkpi.jpeg',
        'items'       => [
            'Program pelatihan teknis intensif bidang Teknisi Komputer berbasis kompetensi.',
            'Menguasai perakitan, konfigurasi BIOS/UEFI, dan pemeliharaan perangkat keras (hardware) komputer.',
            'Instalasi sistem operasi, driver management, konfigurasi jaringan lokal, dan optimasi performa sistem.',
            'Melakukan analisis kerusakan (troubleshooting) perangkat keras/lunak dan perbaikan sesuai standar teknis.',
        ],
    ],
    [
        'title'       => 'Computer Operator',
        'org'         => 'Pusat Pelatihan Kerja Pengembangan Industri (PPKPI)',
        'date'        => 'Okt 2024 – Nov 2024',
        'location'    => 'Cipayung, Jakarta',
        'category'    => 'Teknis & Data',
        'icon'        => '📊',
        'badge'       => 'PPKPI',
        'logo'        => 'assets/logo-ppkpi.jpeg',
        'items'       => [
            'Program pelatihan vokasi & kompetensi bidang Operator Komputer.',
            'Pengoperasian Office Suite tingkat lanjut untuk kebutuhan administrasi, analisa lembar kerja data, dan laporan profesional.',
            'Manajemen sistem komputer, pengelolaan file digital terstruktur, dan pemeliharaan sistem pendukung produktivitas.',
        ],
    ],
];

$stats = [

    ['num' => 'HKI', 'label' => 'Hak Cipta Resmi', 'sub' => 'Kemenkumham DJKI'],
    ['num' => '13+', 'label' => 'Riwayat Karir', 'sub' => 'Teknis & Manajerial'],

];

$skills = [
    ['icon' => '🌐', 'title' => 'Web Front-end', 'desc' => 'React, TypeScript, Next.js, Tailwind, HTML, CSS, JavaScript'],
    ['icon' => '🗄️', 'title' => 'Backend & DB', 'desc' => 'Laravel (PHP), Node.js, MySQL, Firebase'],
    ['icon' => '📱', 'title' => 'Mobile Development', 'desc' => 'Flutter, Dart, Kotlin (Android Studio)'],
    ['icon' => '🧰', 'title' => 'Tools & DevOps', 'desc' => 'Git, GitHub, Docker, Postman, VS Code, Figma'],
    ['icon' => '🎨', 'title' => 'Graphic Design & Office', 'desc' => 'Adobe Photoshop, Illustrator, InDesign, Microsoft Office'],
    ['icon' => '🛠️', 'title' => 'Hardware & Service', 'desc' => 'Troubleshooting Komputer, Maintenance Mesin EDC, Repair Gadget'],
    ['icon' => '👥', 'title' => 'Leadership & Team', 'desc' => 'Person In Charge (PIC), Team Leader, Supervisi Tim & Lapangan'],
    ['icon' => '💼', 'title' => 'Bisnis & Perbankan', 'desc' => 'Perbankan (BCA Teller), Akuisisi Merchant B2B, Field Marketing'],
];

$techSkillPills = [
    ['name' => 'Laravel', 'category' => 'Backend', 'icon' => 'laravel', 'color' => '#f55247'],
    ['name' => 'PHP', 'category' => 'Backend', 'icon' => 'php', 'color' => '#777bb4'],
    ['name' => 'React.js', 'category' => 'Frontend', 'icon' => 'react', 'color' => '#61dafb'],
    ['name' => 'Next.js', 'category' => 'Frontend', 'icon' => 'next', 'color' => '#ffffff'],
    ['name' => 'TypeScript', 'category' => 'Frontend', 'icon' => 'ts', 'color' => '#3178c6'],
    ['name' => 'JavaScript', 'category' => 'Frontend', 'icon' => 'javascript', 'color' => '#f7df1e'],
    ['name' => 'HTML5', 'category' => 'Frontend', 'icon' => 'html', 'color' => '#e34f26'],
    ['name' => 'CSS3', 'category' => 'Frontend', 'icon' => 'css', 'color' => '#1572b6'],
    ['name' => 'TailwindCSS', 'category' => 'Frontend', 'icon' => 'tailwind', 'color' => '#38bdf8'],
    ['name' => 'Bootstrap', 'category' => 'Frontend', 'icon' => 'bootstrap', 'color' => '#7952b3'],
    ['name' => 'Flutter', 'category' => 'Mobile', 'icon' => 'flutter', 'color' => '#02569b'],
    ['name' => 'Kotlin', 'category' => 'Mobile', 'icon' => 'kotlin', 'color' => '#7f52ff'],
    ['name' => 'Android', 'category' => 'Mobile', 'icon' => 'android', 'color' => '#3ddc84'],
    ['name' => 'MySQL', 'category' => 'Backend', 'icon' => 'mysql', 'color' => '#4479a1'],
    ['name' => 'Firebase', 'category' => 'Backend', 'icon' => 'firebase', 'color' => '#ffca28'],
    ['name' => 'Git & GitHub', 'category' => 'Tools', 'icon' => 'git', 'color' => '#f05032'],
    ['name' => 'Docker', 'category' => 'Tools', 'icon' => 'docker', 'color' => '#2496ed'],
    ['name' => 'Postman', 'category' => 'Tools', 'icon' => 'postman', 'color' => '#ff6c37'],
    ['name' => 'Figma', 'category' => 'Tools', 'icon' => 'figma', 'color' => '#f24e1e'],
    ['name' => 'VS Code', 'category' => 'Tools', 'icon' => 'vscode', 'color' => '#007acc'],
    ['name' => 'Microsoft Office', 'category' => 'Tools', 'icon' => 'microsoftoffice', 'local_icon' => 'assets/microsoft-office.svg', 'mark' => 'MS', 'color' => '#f25022'],
    ['name' => 'Adobe Photoshop', 'category' => 'Tools', 'icon' => 'ps', 'color' => '#31a8ff'],
    ['name' => 'Adobe Illustrator', 'category' => 'Tools', 'icon' => 'ai', 'color' => '#ff9a00'],
    ['name' => 'Adobe InDesign', 'category' => 'Tools', 'icon' => 'id', 'local_icon' => 'assets/adobe-indesign.svg', 'mark' => 'Id', 'color' => '#ff3366'],
];

$techIcons = ['laravel','react','php','flutter','firebase','html','css','javascript','mysql','git','docker','ts','next','tailwind','kotlin'];

$certificates = [
    [
        'title' => 'The Role Of CLO as a Strategic Partner',
        'category' => 'Non-IT',
        'issuer' => 'QuBisa',
        'date' => '17 Februari 2022',
        'credential' => '2U13QBTZ5YOU7H',
        'image' => 'assets/strategic-partner.jpg',
        'file' => 'assets/strategic-partner.jpg',
    ],
    [
        'title' => 'Menjadi Marketer Tangguh Sesuai Kebutuhan Pasar',
        'category' => 'Non-IT',
        'issuer' => 'QuBisa',
        'date' => '14 Februari 2022',
        'credential' => '5NQKDVRENBJBOV',
        'image' => 'assets/marketer-tangguh.jpg',
        'file' => 'assets/marketer-tangguh.jpg',
    ],
    [
        'title' => 'Pentingnya Penguasaan Digital Di Era Disrupsi',
        'category' => 'IT',
        'issuer' => 'QuBisa',
        'date' => '19 Februari 2022',
        'credential' => 'G9X4DC0RTJQ9KW',
        'image' => 'assets/penguasaan-digital.jpg',
        'file' => 'assets/penguasaan-digital.jpg',
    ],
    [
        'title' => 'Berubah Atau Punah',
        'category' => 'Non-IT',
        'issuer' => 'QuBisa',
        'date' => '16 Februari 2022',
        'credential' => 'GS2DKUXL5371ML',
        'image' => 'assets/berubah-atau-punah.jpg',
        'file' => 'assets/berubah-atau-punah.jpg',
    ],
    [
        'title' => 'Komunikasi Tanpa Sensi',
        'category' => 'Non-IT',
        'issuer' => 'QuBisa',
        'date' => '18 Februari 2022',
        'credential' => 'QWY91MWP2QIBMW',
        'image' => 'assets/komunikasi-tanpa-sensi.jpg',
        'file' => 'assets/komunikasi-tanpa-sensi.jpg',
    ],
    [
        'title' => 'The Teenagers Character Building Program — Roadmap to Success',
        'category' => 'Non-IT',
        'issuer' => 'Bank Mayora / James Gwee Dream Achievers',
        'date' => '13–14 Agustus 2016',
        'credential' => null,
        'image' => 'assets/roadmap-to-success.jpg',
        'file' => 'assets/roadmap-to-success.jpg',
    ],
    [
        'title' => 'Anti Fraud',
        'category' => 'Non-IT',
        'issuer' => 'Sertifikat Pelatihan',
        'date' => null,
        'credential' => null,
        'image' => 'assets/anti-fraud-preview.png',
        'file' => 'assets/anti-fraud.pdf',
    ],
    [
        'title' => 'API',
        'category' => 'IT',
        'issuer' => 'Sertifikat Pelatihan',
        'date' => null,
        'credential' => null,
        'image' => 'assets/api-preview.png',
        'file' => 'assets/api.pdf',
    ],
    [
        'title' => 'Cyber Security',
        'category' => 'IT',
        'issuer' => 'Sertifikat Pelatihan',
        'date' => null,
        'credential' => null,
        'image' => 'assets/cyber-security-preview.png',
        'file' => 'assets/cyber-security.pdf',
    ],
    [
        'title' => 'Digital Transformation Era',
        'category' => 'IT',
        'issuer' => 'Sertifikat Pelatihan',
        'date' => null,
        'credential' => null,
        'image' => 'assets/digital-transformation-era-preview.png',
        'file' => 'assets/digital-transformation-era.pdf',
    ],
    [
        'title' => 'Perilaku di BCA',
        'category' => 'Non-IT',
        'issuer' => 'BCA',
        'date' => null,
        'credential' => null,
        'image' => 'assets/perilaku-di-bca-preview.png',
        'file' => 'assets/perilaku-di-bca.pdf',
    ],
    [
        'title' => 'Piagam Penghargaan Reynaldi Delphiano',
        'category' => 'Non-IT',
        'issuer' => 'Piagam Penghargaan',
        'date' => null,
        'credential' => null,
        'image' => 'assets/piagam-penghargaan-reynaldi-delphiano-preview.png',
        'file' => 'assets/piagam-penghargaan-reynaldi-delphiano.pdf',
    ],
    [
        'title' => 'Sertifikat Excel',
        'category' => 'IT',
        'issuer' => 'Fasz Edu',
        'date' => '8–10 Februari 2022',
        'credential' => '75/faszedu/OSMM-40/II/2022',
        'image' => 'assets/sertifikat-excel-preview.png',
        'file' => 'assets/sertifikat-excel.pdf',
    ],
    [
        'title' => 'UX Writing',
        'category' => 'IT',
        'issuer' => 'Loker Programmer',
        'date' => '12 Februari 2022',
        'credential' => '0035/ITUW/PST/LOKPRO/II/2022',
        'image' => 'assets/loker-programmer-ux-writing-preview.png',
        'file' => 'assets/loker-programmer-ux-writing.pdf',
    ],
    [
        'title' => 'Web Developer: The Art of Our Web',
        'category' => 'IT',
        'issuer' => 'Loker Programmer',
        'date' => '5 Februari 2022',
        'credential' => '0034/WDTAOW/PST/LOKPRO/II/2022',
        'image' => 'assets/loker-programmer-web-developer-preview.png',
        'file' => 'assets/loker-programmer-web-developer.pdf',
    ],
    [
        'title' => 'Vaksinasi Merdeka Anak',
        'category' => 'Non-IT',
        'issuer' => 'Program Vaksinasi Merdeka Anak',
        'date' => null,
        'credential' => null,
        'image' => 'assets/sertifikat-vm-anak-reynaldi-delphiano-preview.png',
        'file' => 'assets/sertifikat-vm-anak-reynaldi-delphiano.pdf',
    ],
];
